### ISSUE TITLE
rad1o initialisation fails because of missing bias-tee

### ISSUE THREAD

**Issue by 9R** [jopohl/urh#1019]
##### Expected Behavior
Use rad1o (a hackRF compatible badge) as sdr in urh spectrum analyser

##### Actual Behavior
Divice initialisation fails with
```
[ERROR::Device.py::log_retcode] HackRF-SET_BIAS_TEE_ENABLED to 0: HACKRF_ERROR_LIBUSB (-1000)
```
Reason: rad1o does not have a software controllable bias tee

I think this issue could resolved in various ways:
 *  Checkbox in the hackRF profile to let urh know there is a rad1o in use which completely disables the bias-tee initialization 
 *  An additional device profile for the rad1o without the bias-tee code
 *  Catch the libusb error without closing the connection

Completel log:
```
[INFO::Device.py::start_rx_mode] HackRF: Starting RX Mode
[INFO::Device.py::log_retcode] HackRF-SETUP (0000000000000000750865d9222da693): Success
[INFO::Device.py::log_retcode] HackRF-SET_FREQUENCY to 433.92M: Success
[INFO::Device.py::log_retcode] HackRF-SET_SAMPLE_RATE to 2M: Success
[INFO::Device.py::log_retcode] HackRF-SET_BANDWIDTH to 2M: Success
[INFO::Device.py::log_retcode] HackRF-SET_RF_GAIN to 0: Success
[INFO::Device.py::log_retcode] HackRF-SET_IF_GAIN to 16: Success
[INFO::Device.py::log_retcode] HackRF-SET_BB_GAIN to 14: Success
[ERROR::Device.py::log_retcode] HackRF-SET_BIAS_TEE_ENABLED to 0: HACKRF_ERROR_LIBUSB (-1000)
[INFO::Device.py::stop_rx_mode] HackRF: Stopping RX Mode: Stop on error
[INFO::Device.py::log_retcode] HackRF-Start RX MODE: Success
[INFO::Device.py::log_retcode] HackRF-STOP RX MODE: Success
[INFO::Device.py::log_retcode] HackRF-CLOSE: Success
[INFO::Device.py::log_retcode] HackRF-EXIT: Success
```

##### Steps To Reproduce

1. Open Spectrum Analyser
2. Select Device: HackRK
3. Update device ID
4. Press Start
5. HackRF not found popup  appears

##### Platform Specifications

 - OS: Arch Linux
 - URH version: 2.9.3
 - Python version: 3.10
 - Installed via pacman
 - rad1o firmware version: REV 05 | 2022-10-26 | Update to upstream HackRF version v2022.09.1
   * output of `$ hackrf_info`
```
hackrf_info version: 2022.09.1
libhackrf version: 2022.09.1 (0.7)
Found HackRF
Index: 0
Serial number: 0000000000000000750865d9222da693
Board ID Number: 3 (rad1o)
Firmware Version: git-73ae522 (API:1.00)
Part ID Number: 0xa0000a30 0x00514743
```

**Comment by 9R** [comment]
I just ran a short test to confirm my theory:
After disabling the bias_tee lines in dev/config.py and dev/native/HackRF.py when running urh from source the rad1o works as expected.

**Comment by andynoack** [comment]
Hey @9R, would you try if the new branch rad1o_support works for you?

**Comment by 9R** [comment]
@andynoack Thank you for the quick response. I just ran a short test with spectrum analyzer, recorder and protocol sniffer and the rad1o works as expected with your changes in the new rad10_support branch.
