### ISSUE TITLE
Please provide new build

### ISSUE THREAD

**Issue by Bigblock** [jopohl/urh#1026]
I can see that there are some changes in the Code, but the builds are not getting updated.

Would be nice, if Johannes or Andreas could provide us with new official builds for Mac, Windows and Linux.

Thanks!

**Comment by jopohl** [comment]
Sure, just released [v2.9.4](https://github.com/jopohl/urh/releases/tag/v2.9.4) - keep hacking like a boss. :fist_right:  :satellite:
