### ISSUE TITLE
RSP1 - the signal is not recorded correctly (incorrect Sample rate)

### ISSUE THREAD

**Issue by nop0x900** [jopohl/urh#1042]
##### Expected Behavior

SDRPlay RSP1 device. If you set the sample rate to 2M and the bandwidth to 125k (250k), then the real sample rate after recording is 500k. And the record length is exactly 4 times less. Well, accordingly, the width of the pulses is also 4 times smaller. With a bandwidth of 500k, the real sample rate is 1M (2M is specified in the settings). If Sample rate 2M, Band width 1M then real sample rate is 2M...

##### Steps To Reproduce

Sample rate 2M, Band width 125k,250k -> real sample rate is 500k
Sample rate 2M, Band width 500k -> real sample rate is 1M
Sample rate 2M, Band width 1M -> real sample rate is 1M

##### Screenshots

![scr1](https://user-images.githubusercontent.com/60018319/228217174-abb773a4-e15d-4818-ae46-fe004e4ba765.pn
![scr2](https://user-images.githubusercontent.com/60018319/228217559-43af1fb9-d42e-4b63-9650-29f89d3bd4f2.png)
g)

##### Platform Specifications

Windows 7 x86, Windows 10 x64, Sdrplay RSP1 (china clone)

**Comment by andynoack** [comment]
The bandwidth does not influence the sample rate.

**Comment by nop0x900** [comment]
> Полоса пропускания не влияет на частоту дискретизации.



> The bandwidth does not influence the sample rate.

Yes. But there is a bug...

**Comment by andynoack** [comment]
I am unsure what exactly the problem is. By the way, you can configure the sample rate of a signal with a click on the (i) button. This is, however, only for displaying purposes (including the calculation of the shown timings).

**Comment by nop0x900** [comment]
> I am unsure what exactly the problem is. By the way, you can configure the sample rate of a signal with a click on the (i) button. This is, however, only for displaying purposes (including the calculation of the shown timings).

Thank you, that's exactly what I do. Only here is the problem with playback, through hack rf (minimal sample rate 2M), and it turns out it does not work correctly. And it's not convenient, you have to set the parameters every time through the (i) button.

**Comment by andynoack** [comment]
Well, playback/replay should not work at all using different sample rates for recording and sending, as the data stream is passed to the sending device directly.
However, if you generate this signal, it is possible. I understand your problem as follows: 
- you record something with SDRplay and sample rate n 
- URH does not set the sample rate you had configured
- bandwidth does not matter as long as you deactivated the lock in the recording dialog. If not, you are going to change the sample rate and this issue has no point.

**Comment by andynoack** [comment]
Closed due to inactivity.
