### ISSUE TITLE
urh does not run in linux mint 20.3

### ISSUE THREAD

**Issue by geckobob** [jopohl/urh#1050]
Installed via pip. "urh --version" gets "2.9.4". 
Running urh with "urh" gets the following:
Traceback (most recent call last):
  File "/usr/local/bin/urh", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/urh/main.py", line 84, in main
    import urh.cythonext.signal_functions
  File "src/urh/cythonext/signal_functions.pyx", line 1, in init urh.cythonext.signal_functions
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

I'm not a programmer. No idea what to do with this.

**Comment by andynoack** [comment]
Please try the URH version from git. There seems to be a version collision with Python/Cython somehow. By the way, the current Mint version is 21.1 and it probably uses a later Python version.

**Comment by sysfu** [comment]
getting the same issue on Elementary OS 7 Horus, will try the git version.

**Comment by sysfu** [comment]
Git install worked, no problems.

**Comment by andynoack** [comment]
Closed due to inactivity
