### ISSUE TITLE
Freezes & Crashes

### ISSUE THREAD

**Issue by TheBarret** [jopohl/urh#1051]
Maintainer becomes a dick after feedback, no point giving him more.

**Comment by andynoack** [comment]
Dude, you are guessing that the application doesn't use multithreading while posting an error log that excepts in mutliprocessing...
Anyway, I'll try to help and created a branch [fix_rtlsdrtcp](https://github.com/jopohl/urh/tree/fix_rtlsdrtcp) for you. Please check it out!

**Comment by TheBarret** [comment]
> Dude, you are guessing that the application doesn't use multithreading while posting an error log that excepts in mutliprocessing... Anyway, I'll try to help and created a branch [fix_rtlsdrtcp](https://github.com/jopohl/urh/tree/fix_rtlsdrtcp) for you. Please check it out!

i did say 'seems' that assumption was made because the UI thread is visibly dropping frames, if im wrong then im wrong ofc.

**Comment by andynoack** [comment]
I would like to close this issue. Can you confirm that the fix works for you?

**Comment by TheBarret** [comment]
> I would like to close this issue. Can you confirm that the fix works for you?

Thats all up to you Mr. Andy, I'm only reporting it and that's where my part stops.

**Comment by andynoack** [comment]
That is not how it works! If you don't want to test the bugfix that I have written for you personally, it is up to you (but rude of course). 
I don't have your hardware to test it, so I'll delete the branch soon (within one week). If you want to give constructive feedback or if you are interested in solving your problem, reach out to me.

**Comment by logmilo15** [comment]
wait how did you implement the fix?

**Comment by TheBarret** [comment]
> wait how did you implement the fix?

I wish, but the maintainer behaves like a dick.
