### ISSUE TITLE
CC1101 conected via SPI

### ISSUE THREAD

**Issue by Fieldy1999** [jopohl/urh#1052]
Is there a way to use a CC1101 convected via SPI interface on a raspberry pi zero 2 w with your software? 

Thanks

**Comment by andynoack** [comment]
For CC1101 communication we have a GUI plugin that uses rfcat as backend, thus if you are using the GUI of URH and a SPI connection is supported by rfcat, this might work.
The smaller PIs as well as other platforms with few RAM are, however, not perfect for URH analyses as this is mostly a pretty RAM/CPU consuming task.

**Comment by Fieldy1999** [comment]
Thank you, I will have a look at rfcat.
