### ISSUE TITLE
ADALM-PLUTO SDR is not recognized

### ISSUE THREAD

**Issue by ahuri** [jopohl/urh#1069]
Hi.

I tried to capture a signal using Pluto-SDR but it's not recognized by URH.
The driver is up-to-date.

##### Steps To Reproduce
1. Go to 'File'
2. Click on 'Record signal...'
3. Choose 'PlutoSDR' under "Device".
4. Click 'Start' to start capturing.

##### Screenshots
![image](https://github.com/jopohl/urh/assets/19533192/d44d43d6-7f36-4120-bdcb-b1df01a99f2a)

![image](https://github.com/jopohl/urh/assets/19533192/f6f215f7-7147-45c7-9911-4e1bc65db0c7)

##### Platform Specifications

 - OS: Windows 10
 - URH version: 2.9.4

**Comment by andynoack** [comment]
Could you test whether your device is recognized by URH under Linux?

**Comment by ahuri** [comment]
I'm on it.
Will update soon

**Comment by ahuri** [comment]
OK.
Finally installed Ubuntu 22.04.3
1. I tried to install URH using snapd - it failed to launch it (because of a Qt issue I could not figure out how to fix).
2. I tried to install it using pip3 - but did not understand how to launch it.
3. I cloned the GitHub repository and executed main.py - but no device is listed but "RTL-TCP" in the recording signal window.

For now, I'm still struggling to make it work.
If you have any solution - please let me know.

**Comment by ahuri** [comment]
OK. Seams like the snapd installation had permissions issues, "sudo urh" worked and the PlutoSDR is recognized!
Have not idea why in Windows it does not work.

**Comment by andynoack** [comment]
Hey, now we are certain that your device is working, that is a plus. Probably it is a driver issue under Windows then. Have you tried to completely remove the Pluto (and in a second step also the related) drivers and install them News?

**Comment by ahuri** [comment]
Yes.
Just for clarification, the Pluto seems to work in SDR# for instance (in Windows).

**Comment by andynoack** [comment]
That is good! I had a look in our Implementation, maybe our backend is not compatible with your driver. Maybe an older or never (guess not) works. If yes, please let us know which driver works and which does not.

**Comment by ahuri** [comment]
I don't think I've ever installed a driver for that SDR...
Just plug and play.

**Comment by Oleg-cbrRR** [comment]
under windows you just have to specify DEVICE IDENFIFIER to "ip:192.168.2.1"

**Comment by luzpaz** [comment]
Any progress here ?

**Comment by andynoack** [comment]
The issue seems to be resolved since November 1st. Thank you, Oleg!
