### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#107]
Hi there,

Really like the look of this program, just wondering if you could possibly post up a youtube video on general usage with an FSK / ASK signal ?

Thanks

**Comment by jopohl** [comment]
Hi  @vsboost,

glad to hear, that you like the program. I will create a little video as soon as I got some time. Probably in the next week.

**Comment by vsboost** [comment]
Thanks, look forward to seeing it in action.

**Comment by jopohl** [comment]
Hi @vsboost ,

I just uploaded a video for an ASK/FSK signal: https://www.youtube.com/watch?v=QqVvEOzKPCs
More videos will follow soon, but this one should get you started. :-)

**Comment by vsboost** [comment]
Thanks for this, excellent video.

**Comment by vsboost** [comment]
Ill close this one, your videos are excellent, keep up the great work.
