### ISSUE TITLE
custom encode/decode plugin: urh_wisun_fsk_plugin

### ISSUE THREAD

**Issue by qianfan-Zhao** [jopohl/urh#1082]
Hi:

I am learning wisun protocol and debug the rf signal with urh, it is a very useful tool and thanks for all developer works. And I had introduced a custom plugin to decode wisun signal and posted in: https://github.com/qianfan-Zhao/urh_wisun_fsk_plugin

Can you add this to wiki page?

Thanks.

**Comment by andynoack** [comment]
Thank you very much, I added it to the Wiki!
