### ISSUE TITLE
issue with fsk demodulation

### ISSUE THREAD

**Issue by heneault** [jopohl/urh#1086]
##### Expected Behavior
demodulation should detect a series of 01010101 as highlighted in the image

##### Actual Behavior
demodulation only detect 00...000 in FSK

Samples/symbol seems to be ok. Filtering was applied. 

##### Screenshots
![Screenshot from 2023-11-10 13-41-49](https://github.com/jopohl/urh/assets/12136696/89a6b157-e7e1-44d1-aac5-c05ca96d5286)

**Comment by jopohl** [comment]
Did you try increasing the error tolerance?

**Comment by andynoack** [comment]
Actually your signal does not look clean at all. I assume that you see many fallbacks to the center if you zoom in far enough. As @jopohl said, you either have to increase the error tolerance or apply a better filter or record the signal in a more clean way.

**Comment by heneault** [comment]
got it I understand what you meant. I used the band pass filter and it fixed it. Thank you for your help.
