### ISSUE TITLE
Bits are not getting properly decoded in URH

### ISSUE THREAD

**Issue by JasleenKaur2308** [jopohl/urh#1092]
I am trying to decode the bit for 4 fsk for 4 different deviations , for positive deviation ( +648 Hz, +1994 Hz ) my bits are correctly decoding with respective symbols (+648 Hz = 00 and +1994 Hz = 01) but for negative deviation (- 648 Hz , - 1994 Hz) my bits are not correctly decoding . what settings i need to change ?

**Comment by andynoack** [comment]
Hey, you could apply a custom decoding using the substitution block. There you are able to replace the decoded bits from URH with a decoding you prefer.

**Comment by JasleenKaur2308** [comment]
I have attached some screenshots also , for positive values its coming correct but its wrong for negative value . According to symbol mapping it should be (+648Hz =00 , +1944 Hz =01 , -1944 Hz =11, -648 Hz = -648 Hz ). Only positive values are decoding properly . 
<img width="942" alt="github1" src="https://github.com/jopohl/urh/assets/127048694/b42aca55-fe69-4622-9b01-52551baa45ee">
<img width="613" alt="github 2" src="https://github.com/jopohl/urh/assets/127048694/c43db67c-a749-44d5-a5d2-7764be70d369">

**Comment by andynoack** [comment]
In demodulated view you are able to move the three centers for 2bit/symbol signals. Please check that they are set properly.

**Comment by JasleenKaur2308** [comment]
Thank you so much @andynoack , now im able to decode the bits.

**Comment by andynoack** [comment]
Great to hear that!
