### ISSUE TITLE
Play .wav created from AOR receiver.

### ISSUE THREAD

**Issue by Yorch23** [jopohl/urh#1095]
It would be possible to add playback in HackRF from URH of .wav files created with AOR receiver with the following characteristics (Not editable in aor):
-30kHz Bandwidth (+/-15kHz)
-38.4 kS.
-16 bit

Thank you.

**Comment by andynoack** [comment]
Direct playback of 16 bit files is problematic as the HackRF only has 8 bit resolution. Generally URH should be able to send signals that can be loaded (also .wav files). Can you describe what happens when you hit the replay button?

**Comment by Yorch23** [comment]
Hello, the resolution is not a problem, the problem is found in the bandwidth and the "Sample Rate", when I take captures in sdrsharp with a value greater than 2.0M, everything is ok. If the recording is with a value less than 2.0M, the transmitted carrier is deformed and is no longer valid. URH does not allow you to go below 2.0M to adjust to the recording IQ values, for example it does not allow you to play 1024M. I attach photos of the original signal obtained with AOR DV10 and reproduced directly in sdrsharp perfect and reproduced in hackrf you can see how the carrier widens above 12.5 "Bandwidth".
![URH_config](https://github.com/jopohl/urh/assets/118568024/24623916-8010-44ff-bf06-0e1175ed4f43)
![Signal_capture](https://github.com/jopohl/urh/assets/118568024/08dba8dc-36dd-42f5-a9f3-b4d447f7d9e0)
![Signal_original](https://github.com/jopohl/urh/assets/118568024/4b01910b-0b2f-4a39-b3e2-be6edf654674)

**Comment by andynoack** [comment]
URH does not make sample rates below 2M accessible for the HackRF because they are not within the specification (see https://hackrf.readthedocs.io/en/latest/hackrf_one.html#features).

You could persuade URH by editing the dev/config.py
but this is on your own and will not make it to an URH release of course.

**Comment by Yorch23** [comment]
a ok!, thanks for you feedback.

**Comment by andynoack** [comment]
You are welcome!
