### ISSUE TITLE
Unable to run the .dmg

### ISSUE THREAD

**Issue by jdcrunchman** [jopohl/urh#1103]
##### Expected Behavior

“main.app” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Running Ventura 13.6.3

##### Steps To Reproduce

1. Go to finder,  and locate directory where main.app is located
2. Click on .dmg
3.  See error mentioned above
##### Platform Specifications

 - OS: Mac OS Ventura
 - Installed via .DMG
<img width="254" alt="Screenshot 2024-02-05 at 5 21 29 PM" src="https://github.com/jopohl/urh/assets/3130169/93ffbf2f-01d1-49b5-bf91-dacf9a045645">

**Comment by jopohl** [comment]
You need to click the "Show in finder button", from there __right click__ the app icon and select "Open". This will create another open dialog with an "Open" option that allows you to really open the file.

I know that's annoying, but this is how Apple implemented their security for unsigned binaries.
