### ISSUE TITLE
Download fails.

### ISSUE THREAD

**Issue by BallscrewBob** [jopohl/urh#1104]
##### Expected Behavior
Maybe just a warning but ability to keep file

##### Actual Behavior
Blocked and deleted by Chrome Version 122.0.6261.95 (Official Build) (64-bit)

##### Steps To Reproduce
Simply selected the file.

##### Screenshots
![image](https://github.com/jopohl/urh/assets/8212730/bad89823-5f4c-49c6-b85b-494d1b514a84)

##### Platform Specifications
Win 10 X64 pro
Avast AV

**Comment by BallscrewBob** [comment]
Update it is ONLY chrome that deletes it other browsers simply show warnings but do allow you to keep the file.

**Comment by andynoack** [comment]
Maybe this is a duplicate of #1102

**Comment by andynoack** [comment]
Closed due to inactivity
