### ISSUE TITLE
v2.9.6 sdrplay error

### ISSUE THREAD

**Issue by xykts** [jopohl/urh#1110]
URH V2.9.6 version cannot load SDRPLAY on Windows 11
It cannot obtain device identifier
Forcing it to start causes an error with the image

![屏幕截图 2024-03-22 163420](https://github.com/jopohl/urh/assets/34007524/310d2607-ff80-4edc-91ee-707b47536c45)
![屏幕截图 2024-03-22 163759](https://github.com/jopohl/urh/assets/34007524/61d4deec-4cd8-4c66-8d18-077ecb64a895)

sdrply API version: V3.09

##### Platform Specifications

 - OS: [WINDOWS 11]
 - URH version: [ 2.9.6]
 - Python version: [ 3.11]
 - Installed via [e.g.Universal.Radio.Hacker-2.9.6-x64.exe ]

**Comment by andynoack** [comment]
Can you verify that it worked with URH v2.9.5? Maybe this is a driver related issue.

**Comment by andynoack** [comment]
Closed due to inactivity
