### ISSUE TITLE
autodetection parameters are incorrect

### ISSUE THREAD

**Issue by kiran809576** [jopohl/urh#1117]
Hi all,

I am trying to demodulate the 2fsk signal (which i generated from the signal generator - VSG60a). The parameters given for generation of 2fsk signal are:
symbol rate: 1Msps
fsk deviation: 100KHz
And I captured this data using HackRF (by directly injecting the VSG data to HackRF), at the receiver side the sample rate and bandwidth are 2Msps and 2MHz respectively.
When the entire captured signal is given for interpretation, it is detecting samples/symbol as 20 (but required is 2Msps/1Msps = 2) and the demodulated data is not matching with the data I have given. But when I extracted some portion of signal using 'Create signal from selection', the samples/symbol is matching to actual value of 2. In this case I found the correct data sequence only once (in some cases few times), but expected a repeated sequence correctly.

I am not understanding this strange behavior of this,
1. For entire signal - parameters are detecting incorrectly.
2. When portion of the signal is extracted, the demodulated data is not as expected. 

Below is the screenshot for my observation:
![Screenshot (61)](https://github.com/jopohl/urh/assets/171122693/5015775a-ec0a-4a07-b33b-f1867d31c754)

here given data is: fe0900ff0000000000000608c004031987

Thank you

**Comment by andynoack** [comment]
We are using a heuristic algorithm which returns the most probable samples/symbol value. In some cases the algorithm fails as you have seen. In your specific case a fine tuning could solve the problem but our goal is that the algorithm works with most signals. A fine tuning for your specific case could decrease the performance for the general case, so I am a little bit afraid to touch the values that are proven to work in many cases.
