### ISSUE TITLE
urh 2.6.9 compiled with USRP support - but USRP isn't appearing in the Devices dropdowns?

### ISSUE THREAD

**Issue by victorhooi** [jopohl/urh#1119]
##### Expected Behavior

Installing urh with USRP support, it should list "USRP" as an option under Devices in the UI.

(I saw that USRP support was added quite some time back in 2017 - https://github.com/jopohl/urh/issues/133 - hence why I assumed it should probably work out of the box).

##### Actual Behavior

I've installed URP 2.9.6 with USRP support, and I don't seem to see "USRP" as an option in the Device dropdowns.

If I launch urh, and then go to any of the dialogs (e.g. Spectrum Analyzer), and then click on Device - I don't seem to see "USRP" (or anything similar) listed:

![CleanShot 2024-06-06 at 16 31 26@2x](https://github.com/jopohl/urh/assets/243499/ab65b0a9-c09d-4e77-abdd-b3f884c91e24)

##### Steps To Reproduce

1. Install urh via nixpkgs ([package link](https://search.nixos.org/packages?channel=24.05&show=urh&from=0&size=50&sort=relevance&type=packages&query=urh), [package source](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/radio/urh/default.nix))
2. From a terminal, run "urh".
3. Go to File, then Spectrum Analyzer, then click on the "Device" dropdown.
4. Look at the list of devices.

##### Platform Specifications

 - OS: macOS 14.4.1
 - URH version: 2.6.9
 - Python version: [e.g. 3.7]
 - Installed via [Nix packager](https://search.nixos.org/packages?channel=24.05&show=urh&from=0&size=50&sort=relevance&type=packages&query=urh)

I also checked my local build logs for the nix package - it does seem to mention it was compiled with USRP support.

```
Found hackrf lib. Will compile with native hackrf support
Found LimeSuite lib. Will compile with native limesdr support
Found iio lib. Will compile with native plutosdr support
Found rtlsdr lib. Will compile with native rtlsdr support
Found uhd lib. Will compile with native usrp support
Skipping native support for sdrplay
[ 1/12] Cythonizing src/urh/cythonext/auto_interpretation.pyx
[ 2/12] Cythonizing src/urh/cythonext/awre_util.pyx
[ 3/12] Cythonizing src/urh/cythonext/path_creator.pyx
[ 4/12] Cythonizing src/urh/cythonext/signal_functions.pyx
```
Full build logs are here:

https://gist.github.com/victorhooi/540a01284a681cb33cb5aea32fa10ff1

**Comment by victorhooi** [comment]
I went to https://github.com/jopohl/urh/wiki/Supported-devices, and I saw that it mentioned there's an "Options -> Devices" screen.

On macOS, this seems to be under python3.11, Preferences...:

![CleanShot 2024-06-06 at 17 35 37@2x](https://github.com/jopohl/urh/assets/243499/4bab2c41-cf55-476d-954b-09f768b6aed4)

If I open that up, and go to the Devices tab, I noticed that for some reason, USRP was unticked by default:

![CleanShot 2024-06-06 at 17 34 53@2x](https://github.com/jopohl/urh/assets/243499/e1625a3f-372a-4d46-8d95-fa45e97f4411)

I'm thinking that might be my issue - will confirm once I get home.

However, is there a reason that USRP is unticked by defaut? As in, are there any caveats or warnings with this plugin versus the other types?

**Comment by andynoack** [comment]
Usually all SDRs are unticked when you install from source. As you have installed with a package manager, there might be a special crafted package with enabled devices. The driver, however, must be installed beforehand, so in your case the USRP was probably disabled at first. If the driver is installed you should be able to activate it now.

**Comment by Source975** [comment]
airspy -- ERROR: No module named 'urh.dev.native.lib.airspy'
bladerf -- ERROR: No module named 'urh.dev.native.lib.bladerf'
hackrf -- ERROR: No module named 'urh.dev.native.lib.hackrf'
limesdr -- ERROR: No module named 'urh.dev.native.lib.limesdr'
plutosdr -- ERROR: No module named 'urh.dev.native.lib.plutosdr'
rtlsdr -- ERROR: No module named 'urh.dev.native.lib.rtlsdr'
sdrplay -- ERROR: No module named 'urh.dev.native.lib.sdrplay'
usrp -- ERROR: No module named 'urh.dev.native.lib.usrp'
SoundCard -- No module named 'pyaudio'

**Comment by andynoack** [comment]
I will close here because the original issue seems to be solved or inactive. Issues are not for installation support, please visit our Slack channel.

**Comment by andynoack** [comment]
This is not a bug in URH, your installation (Windows/SDR drivers/URH installation) is bugged. Make a clean reinstallation.

**Comment by mono7s** [comment]
> airspy -- ERROR: No module named 'urh.dev.native.lib.airspy' bladerf -- ERROR: No module named 'urh.dev.native.lib.bladerf' hackrf -- ERROR: No module named 'urh.dev.native.lib.hackrf' limesdr -- ERROR: No module named 'urh.dev.native.lib.limesdr' plutosdr -- ERROR: No module named 'urh.dev.native.lib.plutosdr' rtlsdr -- ERROR: No module named 'urh.dev.native.lib.rtlsdr' sdrplay -- ERROR: No module named 'urh.dev.native.lib.sdrplay' usrp -- ERROR: No module named 'urh.dev.native.lib.usrp' SoundCard -- No module named 'pyaudio'

Hello, may I ask if your issue has been resolved? I am facing the same problem and I need your help.

**Comment by mono7s** [comment]
> airspy -- ERROR: No module named 'urh.dev.native.lib.airspy' bladerf -- ERROR: No module named 'urh.dev.native.lib.bladerf' hackrf -- ERROR: No module named 'urh.dev.native.lib.hackrf' limesdr -- ERROR: No module named 'urh.dev.native.lib.limesdr' plutosdr -- ERROR: No module named 'urh.dev.native.lib.plutosdr' rtlsdr -- ERROR: No module named 'urh.dev.native.lib.rtlsdr' sdrplay -- ERROR: No module named 'urh.dev.native.lib.sdrplay' usrp -- ERROR: No module named 'urh.dev.native.lib.usrp' SoundCard -- No module named 'pyaudio'

Or could you please tell me how to successfully use Limesdr after compiling the source code on the Windows platform?
