### ISSUE TITLE
Help about decoding a Manchester signal

### ISSUE THREAD

**Issue by prazsmarid** [jopohl/urh#1126]
Hello,
Can somebody help me to decode the signal?
Using an ASK receiver and a logic analyzer I have got the following format:
0x000000 0x000000 0x000000 0x000000 0x000000 0x000000 0x000000 0x000000 0x000001 0x1F43 0xB 0xFA628C93328B86B3458
Where 0x000000...0x000001 is the preamble, 0x1F43 is the remote unique ID, 0xB (which can be 0xD, 0x7) is the pressed button, 0xFA... is the rolling code.
I have attached here the file made by the URH:
[MQB-again3-RTL-SDR-20240706_092847-433_92MHz-3_2MSps-3_2MHz.zip](https://github.com/user-attachments/files/16115185/MQB-again3-RTL-SDR-20240706_092847-433_92MHz-3_2MSps-3_2MHz.zip)
I have recorded the signal using an RTL-SDR v3 set to 433.92MHz, but for some reason the bit lengths are not equally.
Thanks in advance.

**Comment by andynoack** [comment]
First of all, this is not the place for individual support, so I will close here and recommend to talk to us or our community on Slack.

But I had a short look into your signal that seems pretty clean overall. I can confirm an ASK modulation and a "bit length" in the near of 500 samples per symbol. I cannot find your mentioned hex sequences in any of the decodings incl. Manchester. Additionally there are some decoding errors with Manchester 1/2 that either indicate a different encoding at the beginning of your signals or maybe even no Manchester at all.
