### ISSUE TITLE
How to add rtl-sdr support to urh

### ISSUE THREAD

**Issue by Laozi1527** [jopohl/urh#1127]
After hours of looking through this repo and searching for soloutions for adding support of the rtl-sdr dongle to uhr and not succeding I decided to open an issue here. I would be gratefull if somebody could explain how its done. I installed urh from source and have the rtl blog drivers(Linux).  #1043  has the same issue as me but the last comment couldn't help me. Others apperantly made it work but nowhere has it been ever written down how to do it so please explain it for me.

- Linux distro
- RTL-SDR

**Comment by andynoack** [comment]
Hey, you need to install the linux drivers for your SDR at first, e.g.
`apt install librtlsdr`
or
`apt install librtlsdr-dev`
Then re-install URH or rebuild the cython extensions (`python cythonext/build.py`).
See our Wiki for further dependencies: https://github.com/jopohl/urh/wiki/Dependencies
