### ISSUE TITLE
IQ csv file demodulate

### ISSUE THREAD

**Issue by kiran809576** [jopohl/urh#1128]
Hi,

I have a csv file with IQ samples. Instead of doing demodulation using the exe in windows. I want to simply give this file as argument in a Linux system and store the demodulated binary data in a text file.
Simply, instead of using application in windows, i want to run like commands in Linux. 
Someone please help me out how to do this.

Thank you.

**Comment by andynoack** [comment]
Hey, please have a look in our Wiki: https://github.com/jopohl/urh/wiki/Command-Line-Interface

**Comment by kiran809576** [comment]
If I just give the IQ file as input, will this command line interface autodetect the parameters? Or do I need to pass the required parameters for demodulation as the input arguments?
