### ISSUE TITLE
Getting no signals pls help

### ISSUE THREAD

**Issue by Austriana** [jopohl/urh#1132]
Hey,
I am using an RTL SDR V4 on Win 10.
My problem is i dont get any Signals in. 
When i go to SDR sharp everything works fine.
Anyone experience the same issue?

Marco

**Comment by Austriana** [comment]
![image](https://github.com/user-attachments/assets/bd708f86-ee0c-4080-a221-a3252624b15e)

**Comment by Austriana** [comment]
![image](https://github.com/user-attachments/assets/7bc26cad-fb5c-45d2-aa37-9ef189798690)

**Comment by andynoack** [comment]
Looks like a duplicate of #1118. Does the solution included in the mentioned issue work for you?

**Comment by Austriana** [comment]
Thanks for the tipp! I am very busy at work rn. But i will try that as fast as possible!

**Comment by Austriana** [comment]
Hey @andynoack !!
It works, i got the fix with your Help!! Thank you very much :)

Marco

**Comment by Austriana** [comment]
If anyone having the same issue follow this link https://github.com/jopohl/urh/issues/1132#issuecomment-2299916012

**Comment by Austriana** [comment]
If anyone have the same issue ---> https://www.rtl-sdr.com/v4/
