### ISSUE TITLE
BladeRF Bandwidth Cannot Go Below 1.5MHz

### ISSUE THREAD

**Issue by TraeMazza** [jopohl/urh#1140]
##### Expected Behavior
Editing the bandwidth value in the Bandwidth (Hz) field works as intended with the BladeRF. Entering a value lower than 1.5MHz should work. 

##### Actual Behavior
The Bandwidth (Hz) field does not accept a value lower than 1.5Mhz. If a lower bandwidth is entered, once you leave the textbox, it resets to 1.5M. Going higher in bandwidth works okay.
I tested with another SDR, the RTL-SDR, and did not have the same issue. I suspect that the issue is specific to the BladeRF.

##### Steps To Reproduce
1. Go to Spectrum Analyzer or Signal Recorder
2. Connect a BladeRF device
3. Select BladeRF from device list
4. Click the automatically detect button to ensure the BladeRF is recognized
5. Add a value smaller than 1.5M to the Bandwidth (Hz) field, such as 1.1M
6. Click out of the text box

##### Screenshots
![image](https://github.com/user-attachments/assets/3b6d7a8a-3cea-4fa0-a9b9-123726538ed1)

##### Platform Specifications
OS: Windows 10
URH Version: 2.9.6
Python Version: 3.11.9
Installed via URH Windows EXE instaler

**Comment by andynoack** [comment]
Hey, 

the bladeRF specification, we have used, says 1.5M for bandwidth (see http://www.nuand.com/bladeRF-brief.pdf). If you like to work outside the specs, you can edit /src/urh/dev/config.py:39 on your own risk.

Best regards
Andreas
