### ISSUE TITLE
UserWarning: Distutils was imported before Setuptools

### ISSUE THREAD

**Issue by heiko-git** [jopohl/urh#1142]
##### Expected Behavior
start urh without warning

##### Actual Behavior
starting urh starts with the message:
/home/xxx/.local/pipx/shared/lib/python3.10/site-packages/_distutils_hack/__init__.py:16: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/home/xxx/.local/pipx/shared/lib/python3.10/site-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

##### Steps To Reproduce

1. installed urh : `pipx install urh`
2. needed to change numpy-version : `pipx runpip urh install numpy==1.26.4`
3. try to update setuptools : `pipx runpip urh install setuptools` , but  get message: "Requirement already satisfied: setuptools in ./.local/pipx/shared/lib/python3.10/site-packages (75.1.0)"
4. run `urh` in console

##### Platform Specifications

 - OS: Ubuntu 22.04.2 LTS , Kernel: 6.8.0-45-generic
 - URH version: 2.9.6
 - Python version: 3.10.12
 - Installed via pipx

When I looked for the issue I found a lot of "update setuptools fixes the issue" but it seems not to work for me:
`pipx runpip urh install setuptools`
`Requirement already satisfied: setuptools in ./.local/pipx/shared/lib/python3.10/site-packages (75.1.0)`

**Comment by jopohl** [comment]
Fixed with 2.9.8.
