### ISSUE TITLE
Frequency adjustment

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#129]
Not sure if its just me but i notice when entering a frequency manually in the spectrum analyzer i get some strange behavior.

![image](https://cloud.githubusercontent.com/assets/11001973/22995764/4491ddb8-f420-11e6-8ed4-b7f6283e66be.png)

when replacing the 9 in 433.900 with any other number all the numbers change.

**Comment by jopohl** [comment]
Thanks for reporting this @vsboost 

I was able to reproduce the issue and fixed it in 3b9a86d1d8fffcd85372440a1b15cf31f5bb93dc. Could you verify it works for you, too?

**Comment by vsboost** [comment]
Thank you, working well.

keep up the great work.  love this
