### ISSUE TITLE
Installing on windows error

### ISSUE THREAD

**Issue by stevevaius77** [jopohl/urh#141]
On windows 7 (Ultimate 64 bit), with python 3.5 (32 bit) I can not install urh via command `

> python -m pip install urh

I am receiving error
ImportError: No module named src.urh.version
What should I do to run it on windows

**Comment by jopohl** [comment]
Could you try uninstalling Python 3.5 (32 bit) and install Python 3.5 (64 bit)  or Python 3.6 (64 bit) instead?

**Comment by stevevaius77** [comment]
Still same problem 
![image](https://cloud.githubusercontent.com/assets/24809488/23155423/991938e8-f823-11e6-9ab3-f3bd89b1e604.png)

**Comment by stevevaius77** [comment]
Same problem still
![image](https://cloud.githubusercontent.com/assets/24809488/23155507/e3c98802-f823-11e6-8b78-e01d13cbda82.png)

**Comment by jopohl** [comment]
I can see from your Output, that you are using python 2.7. URH requires atleast python 3.4.

**Comment by stevevaius77** [comment]
Ok, I will change it now and try again :) Thnx

**Comment by jopohl** [comment]
You're welcome. :)

**Comment by stevevaius77** [comment]
Now it installed but dont knwo how to run because >urh command in cmd not working. Any help? :)
![image](https://cloud.githubusercontent.com/assets/24809488/23156656/f7f85006-f828-11e6-8e5e-2c769911dc91.png)

**Comment by jopohl** [comment]
It should be found in ``` c:\users\rustu\appdata\local\programs\python36\lib\site-packages``` . If it is there, you may add this directory to your Windows Path.

**Comment by stevevaius77** [comment]
Do I have to add path of \site-packages or \site-packages\urh? I added full
path bu copying (no error) of site-packages but still gives error when try
it by command >urh or >python urh

Any other help?

**Comment by jopohl** [comment]
Did you find ``` urh.exe ``` in this path? If so, you should add the full path ``` c:\users\rustu\appdata\local\programs\python36\lib\site-packages ``` to your PATH variable. 

Unfortunately, I currently have no Windows for testing available right now. In some subfolder of ``` c:\users\rustu\appdata\local\programs\python36 ``` a ``` urh.exe ``` should be placed. Can you search for it? 

I will have access to my WindowsVM this evening if it still not works for you till then.

**Comment by stevevaius77** [comment]
Thanks. I found the path (in scripts folder) and it loaded but still gives
error as following

[image: Inline image 1]

**Comment by jopohl** [comment]
I can not see your image. :wink:

**Comment by stevevaius77** [comment]
windows qt plugin error

![image](https://cloud.githubusercontent.com/assets/24809488/23159156/c3a877d6-f832-11e6-875a-aa182e4cadb8.png)

**Comment by jopohl** [comment]
That looks bad. Can you run:
```
python -c "from PyQt5 import QtWidgets"
```

**Comment by stevevaius77** [comment]
I did it and after tried to commands again. Nope

**Comment by jopohl** [comment]
I just want to verify, that your PyQt Installation is alrigth. Does this command give you an error:
```python 
python -c "from PyQt5.QtWidgets import QApplication; import sys; app = QApplication(sys.argv); app.exec_()"
```
You can close the terminal if no error occurs to end it.

**Comment by stevevaius77** [comment]
If that was the code, here is result and still have problem
![image](https://cloud.githubusercontent.com/assets/24809488/23160083/2d3cbf4c-f836-11e6-84da-c5698befe87e.png)

**Comment by jopohl** [comment]
Yes...seems your PyQt5 installation itself is kind of broken. Can you try:
```
pip install pyqt5
```
instead
```
python -m pip install pyqt5
```
just to verify, pip is in your PATH.

**Comment by stevevaius77** [comment]
![image](https://cloud.githubusercontent.com/assets/24809488/23160238/c62e0a3a-f836-11e6-8c0a-91b621ff5798.png)

**Comment by jopohl** [comment]
Seems PyQt5 itself is broken here. I guess a .dll is missing or something like that. I found [this stackeroverflow thread](https://stackoverflow.com/questions/20495620/qt-5-1-1-application-failed-to-start-because-platform-plugin-windows-is-missi) suggesting to set the enviroment variable
```
QT_QPA_PLATFORM_PLUGIN_PATH=%QTDIR%\plugins\platforms\ 
```

**Comment by stevevaius77** [comment]
Thanks till now, but how I can set it and I guess missing dll libegl.dll.
But again where to add this?

**Comment by andynoack** [comment]
There is a small tutorial on how to set environment variables under different Windows versions: http://www.computerhope.com/issues/ch000549.htm
Have you tried something similar with the line suggested by Johannes yet?

**Comment by stevevaius77** [comment]
I tried to add environment variable and adding libEGL.dll to "/platforms"
folder. No success. I have another machine which has Debian and windows
installed. I will try there too on windows

**Comment by andynoack** [comment]
Maybe you can try the following with all the necessary libraries in the current path:
```urh.exe -platformpluginpath .```

**Comment by stevevaius77** [comment]
Can you clarify a bit?

**Comment by andynoack** [comment]
The ```-platformpluginpath .``` parameter should make urh to look for the necessary libraries in the current path. If something, e.g. libEGL.dll, cannot be found otherwise, this might help out.
However, your problem seems to be a QT5 problem. Which QT5 version do you use?

**Comment by jopohl** [comment]
I just fired up a fresh Windows 7 VM and could install and run URH like a charm. @stevevaius77  maybe try to run urh from an admin terminal?

**Comment by stevevaius77** [comment]
Ok I will try it Thnx

**Comment by chibill** [comment]
I am able to run it. Easiest way to launch is python -m urh.main

**Comment by stevevaius77** [comment]
Same result :(
"Will not regenerate UI, because script cant be found. This is okay in
release.
This application failed to start because it could not find or load the Qt
platform plugin "windows"
in "".

Reinstalling the application may fix this problem."

**Comment by chibill** [comment]
Do you have pip updated and also the C++ thingy installed.

**Comment by andynoack** [comment]
Hey @stevevaius77, does it work now? Can we close here?

**Comment by stevevaius77** [comment]
yes the issue maybe specific to my system. I couldnt try on another windows os but no need to keep it open. Thnx
