### ISSUE TITLE
Implement native rtlsdr-interface

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#149]
- [x] Create cython wrapper
- [x] Python client code

See https://github.com/jopohl/urh/issues/139

**Comment by JonTabor** [comment]
Question: will support for direct sampling on rtlsdr dongles be included in this, or should I submit it as a new feature request?

**Comment by jopohl** [comment]
I already implemented it in the backend and added it to GUI feature request list in https://github.com/jopohl/urh/issues/148. It will be coming!

**Comment by JonTabor** [comment]
Fantastic, thank you!  Now I can finally try and figure out what that RTTY-like signal is on 8.692MHz...
