### ISSUE TITLE
Unresolved external symbol (RTLSDR)

### ISSUE THREAD

**Issue by cimba007** [jopohl/urh#159]
[output.txt](https://github.com/jopohl/urh/files/801111/output.txt)

Before the latest merge of fix_windows_native it was at least building .. now I got missing external symbol. What am I missing?

I have installed gnuradio from the windows-installer.

**Comment by jopohl** [comment]
Seems to me, you are using a 32 Bit version of python. We only support the 64 Bit version.

**Comment by cimba007** [comment]
Thanks, would be easy if this is the point ;_)

**Comment by jopohl** [comment]
Glad the native backend is working for you now. :+1: 

Gnuradio backend for windows will be fixed in: https://github.com/jopohl/urh/pull/147, which is nearly done. New release should be ready today or tomorrow.

**Comment by cimba007** [comment]
Very nice work you guys put up there. Keep it going!!!
