### ISSUE TITLE
More info on wav file import

### ISSUE THREAD

**Issue by vikbez** [jopohl/urh#160]
Can you add more info on wav file import ?
I tried many different formats but could not get it to work properly

**Comment by andynoack** [comment]
Hey @vikbez,
try the following Wave-Format: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 8 bit, mono.
Furthermore you have to know whether your wave-files are quadrature demulated or not. You can configure this in the checkbox popping up when loading a file via File->Open...

**Comment by cimba007** [comment]
After I got some problems on capturing signals with urh ( https://github.com/jopohl/urh/issues/161 ) I tried to record some audio in sdr-sharp an tried to import it.

None of the two 8-bit-PCM files are working. Am I missing something huge here?

![image](https://cloud.githubusercontent.com/assets/3453121/23331185/31d8f2ea-fb61-11e6-9e24-60b0496fc477.png)

![image](https://cloud.githubusercontent.com/assets/3453121/23331187/39115020-fb61-11e6-9a09-72df45eaa4ba.png)


![image](https://cloud.githubusercontent.com/assets/3453121/23331189/40f8447e-fb61-11e6-9f5a-986c9accf90a.png)

**Comment by andynoack** [comment]
Would you upload one of your recorded wave-files? This would help us analyze the problem very much!

**Comment by cimba007** [comment]
I uploaded both files:

https://mega.nz/#F!Pw4RGCJR!35-l9vpcGBrFbHZjIUAxgA

The AF-Files contains the audio-signal as AM-Modulation:

![image](https://cloud.githubusercontent.com/assets/3453121/23331395/787b950a-fb65-11e6-8558-83f642e2370f.png)

**Comment by andynoack** [comment]
Thank you, I will have a look on it!

**Comment by cimba007** [comment]
Problem might be on my end .. apparently it is not correctly exported to 8bit-mono .. trying to convert the sdr-sharp file afterwards.

**Comment by andynoack** [comment]
Great! Can we close this issue?

**Comment by cimba007** [comment]
I did't open it but for now I am totally fine with the workaround with audacity.

**Comment by vikbez** [comment]
👍  thanks, works with 8bit-mono

**Comment by nofxmrngstr11** [comment]
hello im having trouble saving or even opening any recorded signals in urh. everytime i attempt to save a recorded signal the app just closes out. then im left with this error in my terminal:

"/snap/urh/9/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 2 leaked semaphores to clean up at shutdown
  len(cache))"

im using parrot sec os btw. any suggestions or possible solutions?

**Comment by andynoack** [comment]
This is actually not the right place for a new issue. As you can see in your stack trace the error occurs in the python libs. If you open a new issue on that, ensure that the place where URH produces the error is within the stacktrace. I assume that this is a library/dependency bug not specific to URH, however.
