### ISSUE TITLE
Spectrum analyzer crashes on close

### ISSUE THREAD

**Issue by cimba007** [jopohl/urh#163]
I noticed that upon closing the "Spectrum Analyzer" python crashes. Even if I stopped the capturing with the STOP button:

![image](https://cloud.githubusercontent.com/assets/3453121/23332065/90c9e0e6-fb72-11e6-933e-91f4a1b1ae63.png)

**Comment by andynoack** [comment]
Thank you for the hint, we are searching for a solution!

**Comment by jopohl** [comment]
Should be fixed with **fe1466813b7c619a7147c4dbc3ae3e7a7aade117**. Let me know, if it still occurs!
