### ISSUE TITLE
Sample rate limitations

### ISSUE THREAD

**Issue by mehdideveloper** [jopohl/urh#166]
Is there the possibility to put some limitations on the sample rate value?
For example AirSpy accepts only two values: 2.5MSPS and 10MSPS. 
It's not an important thing; Just a small recommendation

**Comment by jopohl** [comment]
Thanks for the hint @mehdideveloper 

Limiting sample rates (and available gains etc.) will be possible with https://github.com/jopohl/urh/issues/148 .

**Comment by jopohl** [comment]
Added this to task list in https://github.com/jopohl/urh/issues/148. Will close this one.
