### ISSUE TITLE
Unable to install latest update on Windows 10 64 bit

### ISSUE THREAD

**Issue by chibill** [jopohl/urh#167]
> Requirement already satisfied: numpy in c:\python35\lib\site-packages (from urh)
Requirement already satisfied: psutil in c:\python35\lib\site-packages (from urh)
Requirement already satisfied: pyzmq in c:\python35\lib\site-packages (from urh)
Installing collected packages: urh
  Running setup.py install for urh ... error
    Complete output from command C:\Python35\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\chibi\\AppData\\Local\\Temp\\pip-build-2p3hrxnv\\urh\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\chibi\AppData\Local\Temp\pip-1qupfc9k-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\urh
    copying src\urh\constants.py -> build\lib.win32-3.5\urh
    copying src\urh\FFTSceneManager.py -> build\lib.win32-3.5\urh
    copying src\urh\LiveSceneManager.py -> build\lib.win32-3.5\urh
    copying src\urh\main.py -> build\lib.win32-3.5\urh
    copying src\urh\SceneManager.py -> build\lib.win32-3.5\urh
    copying src\urh\SignalSceneManager.py -> build\lib.win32-3.5\urh
    copying src\urh\version.py -> build\lib.win32-3.5\urh
    copying src\urh\__init__.py -> build\lib.win32-3.5\urh
    creating build\lib.win32-3.5\urh\awre
    copying src\urh\awre\CommonRange.py -> build\lib.win32-3.5\urh\awre
    copying src\urh\awre\FormatFinder.py -> build\lib.win32-3.5\urh\awre
    copying src\urh\awre\__init__.py -> build\lib.win32-3.5\urh\awre
    creating build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\Address.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\Component.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\Flags.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\Length.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\Preamble.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\SequenceNumber.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\Type.py -> build\lib.win32-3.5\urh\awre\components
    copying src\urh\awre\components\__init__.py -> build\lib.win32-3.5\urh\awre\components
    creating build\lib.win32-3.5\urh\controller
    copying src\urh\controller\CompareFrameController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\DecoderWidgetController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\FuzzingDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\GeneratorTabController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\MainController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\MessageTypeDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\ModulatorDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\OptionsController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\PluginController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\ProjectDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\ProtocolLabelController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\ProtocolSniffDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\ReceiveDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\SendDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\SendRecvDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\SignalDetailsController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\SignalFrameController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\SignalTabController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\SpectrumDialogController.py -> build\lib.win32-3.5\urh\controller
    copying src\urh\controller\__init__.py -> build\lib.win32-3.5\urh\controller
    creating build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\analyze.py -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\build.py -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\__init__.py -> build\lib.win32-3.5\urh\cythonext
    creating build\lib.win32-3.5\urh\dev
    copying src\urh\dev\BackendHandler.py -> build\lib.win32-3.5\urh\dev
    copying src\urh\dev\PCAP.py -> build\lib.win32-3.5\urh\dev
    copying src\urh\dev\VirtualDevice.py -> build\lib.win32-3.5\urh\dev
    copying src\urh\dev\__init__.py -> build\lib.win32-3.5\urh\dev
    creating build\lib.win32-3.5\urh\dev\gr
    copying src\urh\dev\gr\AbstractBaseThread.py -> build\lib.win32-3.5\urh\dev\gr
    copying src\urh\dev\gr\ReceiverThread.py -> build\lib.win32-3.5\urh\dev\gr
    copying src\urh\dev\gr\SenderThread.py -> build\lib.win32-3.5\urh\dev\gr
    copying src\urh\dev\gr\SpectrumThread.py -> build\lib.win32-3.5\urh\dev\gr
    copying src\urh\dev\gr\__init__.py -> build\lib.win32-3.5\urh\dev\gr
    creating build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\bladerf_recv.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\bladerf_send.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\funcube-dongle_recv.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\hackrf_recv.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\hackrf_send.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\InputHandlerThread.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\rtl-sdr_recv.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\usrp_recv.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\usrp_send.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    copying src\urh\dev\gr\scripts\__init__.py -> build\lib.win32-3.5\urh\dev\gr\scripts
    creating build\lib.win32-3.5\urh\dev\native
    copying src\urh\dev\native\Device.py -> build\lib.win32-3.5\urh\dev\native
    copying src\urh\dev\native\HackRF.py -> build\lib.win32-3.5\urh\dev\native
    copying src\urh\dev\native\RTLSDR.py -> build\lib.win32-3.5\urh\dev\native
    copying src\urh\dev\native\__init__.py -> build\lib.win32-3.5\urh\dev\native
    creating build\lib.win32-3.5\urh\dev\native\lib
    copying src\urh\dev\native\lib\__init__.py -> build\lib.win32-3.5\urh\dev\native\lib
    package init file 'src\urh\dev\native\lib\win\__init__.py' not found (or not a regular file)
    package init file 'src\urh\dev\native\lib\win\libhackrf\__init__.py' not found (or not a regular file)
    creating build\lib.win32-3.5\urh\models
    copying src\urh\models\FieldTypeTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\FileFilterProxyModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\FileIconProvider.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\FileSystemModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\FuzzingTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\GeneratorListModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\GeneratorTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\GeneratorTreeModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\LabelValueTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\ParticipantLegendListModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\ParticipantListModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\PLabelTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\PluginListModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\ProtocolLabelListModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\ProtocolTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\ProtocolTreeItem.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\ProtocolTreeModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\RulesetTableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\TableModel.py -> build\lib.win32-3.5\urh\models
    copying src\urh\models\__init__.py -> build\lib.win32-3.5\urh\models
    creating build\lib.win32-3.5\urh\plugins
    copying src\urh\plugins\Plugin.py -> build\lib.win32-3.5\urh\plugins
    copying src\urh\plugins\PluginManager.py -> build\lib.win32-3.5\urh\plugins
    copying src\urh\plugins\__init__.py -> build\lib.win32-3.5\urh\plugins
    creating build\lib.win32-3.5\urh\plugins\AmbleAnalyzer
    copying src\urh\plugins\AmbleAnalyzer\AmbleAnalyzerPlugin.py -> build\lib.win32-3.5\urh\plugins\AmbleAnalyzer
    copying src\urh\plugins\AmbleAnalyzer\AmbleAssignAction.py -> build\lib.win32-3.5\urh\plugins\AmbleAnalyzer
    copying src\urh\plugins\AmbleAnalyzer\__init__.py -> build\lib.win32-3.5\urh\plugins\AmbleAnalyzer
    creating build\lib.win32-3.5\urh\plugins\InsertSine
    copying src\urh\plugins\InsertSine\InsertSinePlugin.py -> build\lib.win32-3.5\urh\plugins\InsertSine
    copying src\urh\plugins\InsertSine\__init__.py -> build\lib.win32-3.5\urh\plugins\InsertSine
    creating build\lib.win32-3.5\urh\plugins\MessageBreak
    copying src\urh\plugins\MessageBreak\MessageBreakAction.py -> build\lib.win32-3.5\urh\plugins\MessageBreak
    copying src\urh\plugins\MessageBreak\MessageBreakPlugin.py -> build\lib.win32-3.5\urh\plugins\MessageBreak
    copying src\urh\plugins\MessageBreak\__init__.py -> build\lib.win32-3.5\urh\plugins\MessageBreak
    creating build\lib.win32-3.5\urh\plugins\NetworkSDRInterface
    copying src\urh\plugins\NetworkSDRInterface\NetworkSDRInterfacePlugin.py -> build\lib.win32-3.5\urh\plugins\NetworkSDRInterface
    copying src\urh\plugins\NetworkSDRInterface\__init__.py -> build\lib.win32-3.5\urh\plugins\NetworkSDRInterface
    creating build\lib.win32-3.5\urh\plugins\ZeroHide
    copying src\urh\plugins\ZeroHide\ZeroHideAction.py -> build\lib.win32-3.5\urh\plugins\ZeroHide
    copying src\urh\plugins\ZeroHide\ZeroHidePlugin.py -> build\lib.win32-3.5\urh\plugins\ZeroHide
    copying src\urh\plugins\ZeroHide\__init__.py -> build\lib.win32-3.5\urh\plugins\ZeroHide
    creating build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\encoder.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\FieldType.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\Interval.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\Message.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\MessageType.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\Modulator.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\Participant.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\ProtocoLabel.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\ProtocolAnalyzer.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\ProtocolAnalyzerContainer.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\ProtocolGroup.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\ProtocolSniffer.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\Ruleset.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\Signal.py -> build\lib.win32-3.5\urh\signalprocessing
    copying src\urh\signalprocessing\__init__.py -> build\lib.win32-3.5\urh\signalprocessing
    creating build\lib.win32-3.5\urh\ui
    copying src\urh\ui\CustomDialog.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\GeneratorListWidget.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\GridScene.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\KillerDoubleSpinBox.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\LabeledArrow.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\LegendScene.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ListWidget.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ROI.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\SaveAllDialog.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ScrollArea.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_analysis_frame.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_decoding.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_fuzzing.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_generator.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_main.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_messagetype_options.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_modulation.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_options.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_plugins.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_project.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_properties_dialog.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_send_recv.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_signal_details.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_signal_frame.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ui_tab_interpretation.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\urh_rc.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\WavFileDialog.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\xtra_icons_rc.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\ZoomableScene.py -> build\lib.win32-3.5\urh\ui
    copying src\urh\ui\__init__.py -> build\lib.win32-3.5\urh\ui
    creating build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\ChangeSignalParameter.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\Clear.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\DeleteBitsAndPauses.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\EditSignalAction.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\Fuzz.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\InsertBitsAndPauses.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\InsertColumn.py -> build\lib.win32-3.5\urh\ui\actions
    copying src\urh\ui\actions\__init__.py -> build\lib.win32-3.5\urh\ui\actions
    creating build\lib.win32-3.5\urh\ui\delegates
    copying src\urh\ui\delegates\CheckBoxDelegate.py -> build\lib.win32-3.5\urh\ui\delegates
    copying src\urh\ui\delegates\ComboBoxDelegate.py -> build\lib.win32-3.5\urh\ui\delegates
    copying src\urh\ui\delegates\SpinBoxDelegate.py -> build\lib.win32-3.5\urh\ui\delegates
    copying src\urh\ui\delegates\__init__.py -> build\lib.win32-3.5\urh\ui\delegates
    creating build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\DirectoryTreeView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\EditableGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\EpicGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\FuzzingTableView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\GeneratorListView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\GeneratorTableView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\GeneratorTreeView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\LabelValueTableView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\LegendGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\LiveGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ModulatorTreeView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ProtocolLabelListView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ProtocolLabelTableView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ProtocolTableView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ProtocolTreeView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\SelectableGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\TableView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\TextEditProtocolView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ZoomableGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\ZoomAndDropableGraphicView.py -> build\lib.win32-3.5\urh\ui\views
    copying src\urh\ui\views\__init__.py -> build\lib.win32-3.5\urh\ui\views
    creating build\lib.win32-3.5\urh\util
    copying src\urh\util\crc.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\Errors.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\FileOperator.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\FontHelper.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\Formatter.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\Logger.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\ProjectManager.py -> build\lib.win32-3.5\urh\util
    copying src\urh\util\__init__.py -> build\lib.win32-3.5\urh\util
    package init file 'src\urh\__pycache__\__init__.py' not found (or not a regular file)
    copying src\urh\cythonext\path_creator.cpp -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\signalFunctions.cpp -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\util.cpp -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\path_creator.pyx -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\signalFunctions.pyx -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\cythonext\util.pyx -> build\lib.win32-3.5\urh\cythonext
    copying src\urh\dev\native\lib\hackrf.cpp -> build\lib.win32-3.5\urh\dev\native\lib
    copying src\urh\dev\native\lib\rtlsdr.cpp -> build\lib.win32-3.5\urh\dev\native\lib
    copying src\urh\dev\native\lib\hackrf.pyx -> build\lib.win32-3.5\urh\dev\native\lib
    copying src\urh\dev\native\lib\rtlsdr.pyx -> build\lib.win32-3.5\urh\dev\native\lib
    copying src\urh\dev\native\lib\chackrf.pxd -> build\lib.win32-3.5\urh\dev\native\lib
    copying src\urh\dev\native\lib\crtlsdr.pxd -> build\lib.win32-3.5\urh\dev\native\lib
    creating build\lib.win32-3.5\urh\dev\native\lib\win
    copying src\urh\dev\native\lib\win\COPYING.libusbx -> build\lib.win32-3.5\urh\dev\native\lib\win
    copying src\urh\dev\native\lib\win\COPYING.pthreads-win32 -> build\lib.win32-3.5\urh\dev\native\lib\win
    copying src\urh\dev\native\lib\win\hackrf.dll -> build\lib.win32-3.5\urh\dev\native\lib\win
    copying src\urh\dev\native\lib\win\hackrf.lib -> build\lib.win32-3.5\urh\dev\native\lib\win
    error: can't copy 'src\urh\dev\native\lib\win\libhackrf': doesn't exist or not a regular file

    ----------------------------------------
Command "C:\Python35\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\chibi\\AppData\\Local\\Temp\\pip-build-2p3hrxnv\\urh\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\chibi\AppData\Local\Temp\pip-1qupfc9k-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\chibi\AppData\Local\Temp\pip-build-2p3hrxnv\urh\

**Comment by chibill** [comment]
Do I have to have a 64 bit version of Py3 to install and use urh??? After the recent update to get the rtl_sdr wroking?

**Comment by jopohl** [comment]
Hey @chibill ,

yes you need to have a 64 Bit version of Python 3.

**Comment by chibill** [comment]
When did this become a requirement? Like really...

Also why use 64 but when many of the binary based libs don't have 64 bit
versions example scipy.

But what ever I will see if I can get it to install with out wiping out my
py2... Stupid py3 loves to do that on Windows...


On Feb 27, 2017 12:46 AM, "Johannes Pohl" <notifications@github.com> wrote:

Hey @chibill <https://github.com/chibill> ,

yes you need to have a 64 Bit version of Python 3.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jopohl/urh/issues/167#issuecomment-282641181>, or mute
the thread

**Comment by jopohl** [comment]
I see your point @chibill . I added support for python 3 32 bit again in latest release. Native backends will be disabled and an message will be shown in Device options to indicate that.

**Comment by chibill** [comment]
I am confused why the native back end would not work with 32 bit.and least
I know the rtl_SDR driver has both versions.. (And most python based ones
are 32 bit. Like the one pyrtlsdr uses.

**Comment by jopohl** [comment]
It is just a matter of resources. I simply do not have the time to maintain and test native backends with 32 bit python 3. I thought anyone using this kind of software would use 64 bit python 3 anyway, as you need a couple of  usable RAM to work properly with signals.

That said, if you would like helping increasing the windows support and specifically supporting 32 bit python 3 for native backend, be welcome.

**Comment by chibill** [comment]
The thing is I only had 32 installed because that's what everyone required
at the time for native C stuff. (I have 3.5 installed and I live on py2
because it's stable and also integers works correctly.)

Like I said I will try to get py3 64 working. Just don't want to break tons
of stuff... (Like ipython.)


On Feb 27, 2017 1:46 AM, "Johannes Pohl" <notifications@github.com> wrote:

It is just a matter of resources. I simply do not have the time to maintain
and test native backends with 32 bit python 3. I thought anyone using this
kind of software would use 64 bit python 3 anyway, as you need a couple of
usable RAM to work properly with signals.

That said, if you would like helping increasing the windows support and
specifically supporting 32 bit python 3 for native backend, be welcome.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jopohl/urh/issues/167#issuecomment-282649538>, or mute
the thread

**Comment by jopohl** [comment]
Time goes on and so do dependencies. :wink: 

Furthermore, it sounds to me that you can go on with your exisiting programs, as you are running them with python 2 (32 bit), so this should be untouched by an python 3 (64 bit) installation.

I will close this one. If other problems should arise during installation feel free to open another issue.

**Comment by chibill** [comment]
Okay. Hopefully this works then..
