### ISSUE TITLE
please specify gr-osmosdr dep in readme

### ISSUE THREAD

**Issue by ZeroChaos-** [jopohl/urh#176]
bladerf support as well please.  directly of pull in a bunch of hardware using gr-osmosdr and/or soapysdr support.

**Comment by ZeroChaos-** [comment]
after using for more than 10 seconds, it appears this is already supported.  I suppose my question is "how", so that I can add the appropriate deps (if any) for other users.

**Comment by andynoack** [comment]
Currently BladeRF is only supported via the gnuradio backend. That means, gnuradio + gr-osmosdr should be sufficient to use it.

**Comment by ZeroChaos-** [comment]
Does that mean that gr-osmosdr is a (potential) dep?

**Comment by andynoack** [comment]
Yes it is. Both gnuradio and gr-osmosdr are necessary to enable the gnuradio backend. At the moment I am not sure what happens, if gnuradio is installed without gr-osmosdr...

**Comment by ZeroChaos-** [comment]
Cool, I've updated gentoo and I'll leave this open as a reminder to please update your readme (and anywhere else you feel appropriate) that gr-osmosdr is at least an optional dep.  Might want to specify libhackrf and librtlsdr in the same place.

**Comment by ZeroChaos-** [comment]
awesome, thanks!
