### ISSUE TITLE
Does URH require a 64 bit CPU and/or OS?

### ISSUE THREAD

**Issue by RChadwick7** [jopohl/urh#181]
I have a small tablet I use for SDRSharp. I believe the CPU is a 64 bit Atom, but I have a 32 bit OS, as I only have 2GB. Will URH work on this?

**Comment by jopohl** [comment]
Yes URH will work on this. However, as you are using SDR#, I assume you are on Windows so you will not be able to use native device backends.

**Comment by andynoack** [comment]
I think, we can close here. Feel free to open a new issue if there are further questions!
