### ISSUE TITLE
Save defaults

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#185]
Hi there,

Any chance the program could save defaults for example i notice that FSK is default when opening a file, is it possible that if i select ASK that it will stay that way, and also for recording signals i think USRP is default, would love it if it remembers the last used device for me HackRF and the sample rate and frequency used.

**Comment by jopohl** [comment]
Hey @vsboost ,

what you are describing is the project feature of URH. You can use it by opening a directory (File -> Open) and converting your folder to an URH project if asked. After this, your mentioned configurations will  be saved for this project.

**Comment by vsboost** [comment]
Ahh thanks, didn't realize that.
