### ISSUE TITLE
RTL-SDR to allow start from 0.1 MHz in direct sampling mode

### ISSUE THREAD

**Issue by mrroyh** [jopohl/urh#211]
Hi,
Is there reasons to not allow rtl-sdr to tune below 22MHz?
Some rtl-sdr dongle can tune below that in direct sampling mode.
And I have change my config.py and my rtl-sdr dongle can tune below 22MHz.
Thank you.

**Comment by jopohl** [comment]
Hi @mrroyh ,
I configured this limit based on [this table from osmocom](http://osmocom.org/projects/sdr/wiki/rtl-sdr). Do you own a tuner that is not listed there?

**Comment by mrroyh** [comment]
I have one rtlsdr dongle from [http://www.rtl-sdr.com/buy-rtl-sdr-dvb-t-dongles/](url). It is equiped with R820T2 tuner and was modified to bypass that tuner to allow direct sampling mode in Q-branch of RTL2832U chip.
