### ISSUE TITLE
Shall we implement a Windows/OSX installer? (Thumbs up for yes)

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#212]
The question is whether the current installation routine is too complicated on Windows and OSX. If you really need a installer or think, that might be useful, leave a comment or thumbs up.

**Comment by vsboost** [comment]
Windows installer would be nice for those who find it difficult with building/compiling software.

**Comment by andynoack** [comment]
Do you think there is a large interception of people that find it difficult building software and use SDRs?

**Comment by gustavecha** [comment]
Hi,

Windows installation is really easy :
> pip install urh

Do we really need an installer for that ?
I guess no

**Comment by vsboost** [comment]
Im a member of a few SDR groups and i always hear them complain about linux software or find it difficult to build for windows and install 50 different things just to get it going.

**Comment by vsboost** [comment]
Not that it bothers me, i have dual boot windows/linux.

**Comment by ikarus23** [comment]
I don't think a Windows installer is needed. It is likely that users interested in the features that URH provide (blind signal analysis, fuzzing, etc.) already use Linux.

**Comment by andynoack** [comment]
Thanks for the feedback! I will close here.
