### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by chibill** [jopohl/urh#217]
Make it so you can select the place you want to decode in the packet analyzer (think that's the right GUI) with the mouse.

**Comment by ikarus23** [comment]
If you want to decode just a part of a recoded signal, you can do so by
* marking the part (shift + left click),
* then right click on the selection and
* choose "Create signal from selection".

Hope this helps.

**Comment by andynoack** [comment]
Could you point that out a little bit more?

**Comment by chibill** [comment]
Okay. I was trying alot of stuff to try and get that working.

**Comment by ikarus23** [comment]
But you got it working? And how? Was the method I mentioned sufficient?

**Comment by chibill** [comment]
Yes, This can be closed I guess.
