### ISSUE TITLE
no Frequency Correction option for SDR

### ISSUE THREAD

**Issue by roema** [jopohl/urh#232]
Hi!

I have nothing found about frequency correction for SDR (hackrf).
Is it possible to add a field in the options for SDR to add the correction value in ppm?
 Or is there another option to correct that?

Thanks for you answer!

Manu

**Comment by jopohl** [comment]
Hi @roema ,

unfortunately, there seems to be no method for setting frequency correction in hackrf driver: https://github.com/mossmann/hackrf/blob/master/host/libhackrf/src/hackrf.h

**Comment by roema** [comment]
Hi @jopohl!

Thanks for your message! It's no problem!
UHR is a very grateful tool! Today i have successfully cloned a garge door transmitter (ASK) an the remote car key from my suzuki (FSK) in few minutes!

**Comment by jopohl** [comment]
Glad to hear that @roema - it is a pleasure to see that URH ist helpful.
