### ISSUE TITLE
[LimeSDR Beta] LimeSDR-SET_BANDWIDTH error at 1.4MHz

### ISSUE THREAD

**Issue by romeojulietthotel** [jopohl/urh#234]
Record Signal, Sniff Protocol and Spectrum Analyzer all show this error:

`LimeSDR-SET_BANDWIDTH to 1400000.0: Error Code: -1 (-1)`

Even though URH shows that error I can still record,sniff,analyze so some default must be used.

If I set bandwidth to 2M then that error is not seen. I think this may be an underlying issue on the LimeSDR platform.

**Comment by jopohl** [comment]
I also noticed this error, it comes from the LimeSDR API. I think such low bandwidths are not supported by LimeSDR so I just increased the minimum bandwidth to 2M in b085c10f240c95d8e5a8e82eb7c6222e8fc6ada3.
