### ISSUE TITLE
Zoom In to stay centered.

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#238]
Just realized Ctrl + zooms in.. or in my case i have to hit Ctrl Shift +

Is there a way when zooming in the signal of interest stays centered, i find that it jumps back each time you press Ctrl +

Regards

**Comment by vsboost** [comment]
Using the mouse scroll wheel seems to keep the signal centered which is good.

**Comment by jopohl** [comment]
Hey @vsboost ,

I just fixed the keyboard zoom, it now behaves like the mousewheel zoom and scrolls to the position of the mouse cursor. What do you think about that?

**Comment by vsboost** [comment]
Fantastic, thanks for this.

**Comment by vsboost** [comment]
Sorry ill just re open this one because i noticed that when i select a signal and crop to new selection i can no longer use the Ctrl + to zoom in

**Comment by jopohl** [comment]
I could not reproduce this one. Can you give more details? What I did was: Open a signal, select some samples, right click -> "crop to selection", press Ctrl ++ and Ctrl +-, which worked for me.
How many samples were left in your signal after cropping? The zoom is disabled for signals with less than 300 samples.

**Comment by vsboost** [comment]
Its a strange one, what i found that if i use the touchpad on my tablet to make a selection and right click and crop to selection the new signal that is displayed wont let me zoom using Ctrl +, however if i do the exact same with a mouse it will let me zoom.
Workaround i just discovered is i need to select the new signal and make a selection of any width then i can use the Ctrl + to zoom.

Hope that makes sense, it doesn't bother me now that i know how to make it work, so if you cant reproduce just close this one.

Thanks again

**Comment by jopohl** [comment]
Is it possible, that the new signal just loses the focus? In this case, it should be enough to make a single left click inside the new signal to make zooming work again.

**Comment by vsboost** [comment]
This would be the case.

Cheers
