### ISSUE TITLE
Signal selection

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#239]
Hi,

I noticed in the interpretation tab that in order to select a part of a signal that you must first select some bits first in the window below the signal, is this by design or is it possible to make it so if the mouse button is clicked in the top signal window that the blue selection markers appear?

**Comment by jopohl** [comment]
Hi @vsboost ,
you can make a selection, by holding the SHIFT key and then using the mouse. You can also change this behaviour via options -> view -> hold shift to drag.

**Comment by vsboost** [comment]
Sweet, needed to enable hold shift to drag in options..
