### ISSUE TITLE
Ability to add HEX / ASCII values to fuzzed messages

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#241]
Hi there,

Was wondering if its possible to add Range / Boundaries / Random data in hex / ascii ?

Cheers

**Comment by andynoack** [comment]
I do not know whether I understand you right, but I think you can already do that by changing the view type in the generator before (bottom right)

**Comment by vsboost** [comment]
What i mean is the fuzzed values are only decimal.

**Comment by andynoack** [comment]
Ok, so you would like to see the border/... values in the current view type (hex, ascii) instead of values converted to decimal?

**Comment by vsboost** [comment]
Correct

**Comment by andynoack** [comment]
I think that will be a larger amount of work as we would need special input boxes for that. I am not sure if this really improves the useability (especially for ascii!) or makes it even worse (as you do not see the number of fuzzed values on the first sight). We will discuss that!

**Comment by vsboost** [comment]
Don't stress over it, just me being picky lol.

Can close this one,, id rather you guys focus on other features that benefit everybody.

cheers

**Comment by andynoack** [comment]
Ok, great :-) However, we will talk about that and see what we can do!
