### ISSUE TITLE
"Using modules from /home/user/src" displayed on startup

### ISSUE THREAD

**Issue by romeojulietthotel** [jopohl/urh#244]
Just began seeing this on urh startup. The message is displayed after:
`Will not regenerate UI, because script cant be found. This is okay in release.`

~/src has nothing to do with urh and maybe this message does not make a difference for urh.

BTW cant should be can't or cannot

**Comment by jopohl** [comment]
Thanks for pointing this out. Could you test the fix I wrote?

**Comment by romeojulietthotel** [comment]
Shows same path, i.e. ~/src

**Comment by jopohl** [comment]
How do you run URH? From source?

**Comment by romeojulietthotel** [comment]
From install:

`python setup.py install --without-hackrf --without-rtlsdr
`

then

`urh`

I haven't looked closely but the message seems to be informational only. Is that correct? Or is URH looking there for modules?

**Comment by jopohl** [comment]
Well the purpose of this is to ensure, that the modules are added to the Pythonpath if URH is run from source. In your case, it can be safely ignored, if you can start URH without import errors.

**Comment by romeojulietthotel** [comment]
When I first saw it I was concerned that the app was doing things in that directory. Others may draw a similar conclusion.

**Comment by jopohl** [comment]
Agreed, I just updated the message to avoid confusion.

**Comment by romeojulietthotel** [comment]
It's fine, looks good.
