### ISSUE TITLE
Bit position text size (Windows)

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#249]
Thought i would try URH in Windows just for laughs, and thought i would bring this to your attention.

![image](https://cloud.githubusercontent.com/assets/11001973/25327866/17a91d6a-2919-11e7-950d-56de4eb0bc9d.png)

Using the Microsoft Surface Pro2

**Comment by jopohl** [comment]
Thanks for pointing that out, I never noticed this on Windows, seems to be related with the configured system font. Could you try setting ``` src/urh/ui/views/TableView.py:59 ``` to e.g. ``` w = self.font().pointSize() + 5 ``` and see if that works better?

**Comment by vsboost** [comment]
Is that possible when using pip3 to install URH?

**Comment by jopohl** [comment]
No, you would go this way:
```
git clone https://github.com/jopohl/urh/
cd urh/src/urh
./main.py
```

You can get Git for Windows [https://git-scm.com/download/win](here)

**Comment by jopohl** [comment]
I just had a deeper look at it and pushed a probable fix to master. You can test it out via Git or wait till the next release, which will happen soon.

**Comment by vsboost** [comment]
No probs, ill wait for a release.

**Comment by vsboost** [comment]
Just to let you know, setting it to a value of 7 seemed to do the trick for me.
w = self.font().pointSize() + 7

![image](https://cloud.githubusercontent.com/assets/11001973/25382474/2157d148-29fb-11e7-811c-7350262df810.png)

**Comment by jopohl** [comment]
Do you also need to do this with latest coder on master or is the fix I wrote sufficent?

**Comment by vsboost** [comment]
Yes even with the latest code i still needed to apply the fix.

**Comment by jopohl** [comment]
That's not so good, because adding an absolute offset means that the header will be too wide in other environments. Can you add a
```
print("Font Size", self.font().pointSize())
```
at  ``` urh/ui/views/TableView.py:60 ```  and post the result?

**Comment by vsboost** [comment]
File "c:\users\vsboost\urh\src\urh\ui\views\TableView.py", line 60
    print("Font Size", self.font().pointSize())
                                              ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by jopohl** [comment]
Please indent the new line with spaces only and not use tabs.

**Comment by vsboost** [comment]
I switched themes and it looks fine in the dark theme,

Below is the standard theme
![image](https://cloud.githubusercontent.com/assets/11001973/25384016/ec046414-2a01-11e7-94d5-f6c4d908c28b.png)


below is in the dark theme
![image](https://cloud.githubusercontent.com/assets/11001973/25384041/104e49de-2a02-11e7-93f3-16d0832ce262.png)

Do you still want me to run with the print("Font Size", self.font().pointSize()) ?

**Comment by jopohl** [comment]
Yes, would be very helpful. I suspect, Windows somehow bugs around and reports a pointSize of 0 to Qt. If that is the case, I could catch for 0 and fix it for the native theme.

**Comment by ngmacha** [comment]
I have same problem, but I think it might have something to do with Windows10's font scaling feature, which is automatically set to 125% - 150% on the Surface tablets:
![image](https://cloud.githubusercontent.com/assets/883534/25384162/ec0fae6c-29c7-11e7-83a2-9aa01b2b94c1.png)

If I switch to 100% then everything displays OK...

**Comment by vsboost** [comment]
Font Size 8 is what i get in the console.

Switching from (native look default) to (fallback theme) or (fallback theme dark) fixes the problem without having to exit URH however going back to (native look default) the issue reappears.

Can do a screen record if you need it.

**Comment by vsboost** [comment]
I have mine set to 150% being a surface pro 2 (small screen)

**Comment by jopohl** [comment]
Thanks a lot for pointing this out @ngmacha!

@vsboost : Does setting scale to 100% also solves the problem for you? At least we would know the cause then.

**Comment by vsboost** [comment]
Yep, native look default works when windows scaling is set to 100%.

**Comment by jopohl** [comment]
I was able to reproduce this on windows, by setting the font scaling to 150% and wrote a fix for it. Should work now.

**Comment by vsboost** [comment]
Nice, working well..

Thanks again
