### ISSUE TITLE
You need at least Python 3.4 for this application!

### ISSUE THREAD

**Issue by muhantu** [jopohl/urh#251]
![screenshot from 2017-04-26 14-26-09](https://cloud.githubusercontent.com/assets/25543023/25422843/8524ead0-2a8c-11e7-9762-978201f2b6c2.png)

Anyone can help me?

**Comment by jopohl** [comment]
Try ``` python3.5 setup.py install ``` instead ``` python setup.py install ```.

**Comment by muhantu** [comment]
ok, thanks
I'll try it..

**Comment by muhantu** [comment]
![screenshot from 2017-04-26 15-18-01](https://cloud.githubusercontent.com/assets/25543023/25424723/9ceec4a4-2a93-11e7-9e50-e5deca09a389.png)
this is what i got

**Comment by jopohl** [comment]
You can install pyqt5 by hand if your distribution can't find it with:
```
sudo apt-get update
sudo apt-get install python3-pyqt5
```
Furthermore, you may try ``` python3 setup.py install ```, maybe ``` python3.5 ``` is not linked properly.

**Comment by muhantu** [comment]
`sudo apt-get install python3-pyqt5`

that's didn't take any effect, and than I try yout suggest with python3, that's successful..
thx jopohl :D
