### ISSUE TITLE
LimeSDR disable

### ISSUE THREAD

**Issue by Ancer13** [jopohl/urh#259]
![selection_001](https://cloud.githubusercontent.com/assets/28226126/25565757/c430bdb6-2d8a-11e7-8d9f-07c21940b342.jpg)
  Limesdr disable and cant enable it 
Device extention still showing even restart and log out only in regular user but in sudo nothing detected

Ubuntu 16.04

**Comment by jopohl** [comment]
What does 
```
locate  libLimeSuite.so
```
say?

**Comment by Ancer13** [comment]
locate  libLimeSuite.so
/usr/lib/x86_64-linux-gnu/libLimeSuite.so.17.02-1
/usr/lib/x86_64-linux-gnu/libLimeSuite.so.17.02.2


________________________________

**Comment by jopohl** [comment]
Please do
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libLimeSuite.so.17.02.2 /usr/lib/x86_64-linux-gnu/libLimeSuite.so
```
and try again.

**Comment by Ancer13** [comment]
Yes finally it works thank you very much.
