### ISSUE TITLE
Send via RFcat repeat.

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#260]
Hi there,
I was wondering if its possible to have an auto repeat function available when sending data via RFcat?

Cheers

**Comment by andynoack** [comment]
Hi @vsboost 
I think over it.

**Comment by vsboost** [comment]
Possible to integrate it with the default sending repetitions in options?

**Comment by andynoack** [comment]
Does it work for you?

**Comment by vsboost** [comment]
Thanks for this, working well.
