### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type ZoomableGraphicView 

### ISSUE THREAD

**Issue by wizz777** [jopohl/urh#272]
#Error

ZoomableGraphicView.py", line 52, in scrollContentsBy
    super().scrollContentsBy(dx, dy)
RuntimeError: wrapped C/C++ object of type ZoomableGraphicView has been deleted
Abort trap: 6

## Steps to Reproduce the Problem

  1. Open raw file
  2. go to Generator
  3.  click Edit...
  4. Click Save and Close

## Platform Specifications

  - Python Version: 3.6
  - Operating System: MacOS 10.12.4
  - Version of URH:1.6.2.4

**Comment by jopohl** [comment]
Thanks for reporting this. I wrote fix for it, so you can either check out latest master or wait for next release.

**Comment by jopohl** [comment]
Fixed with [version 1.6.4](https://github.com/jopohl/urh/releases/tag/v1.6.4).
