### ISSUE TITLE
document the --enable-* and --disable-* flags

### ISSUE THREAD

**Issue by ZeroChaos-** [jopohl/urh#274]
you keep adding support for things, and honestly I don't know distutils well enough to dig through the code to see if you added --{disable,enable}-uhd

Please document the flags in README.md

**Comment by jopohl** [comment]
Thanks for the hint. I added documentation for the flags to the wiki page: https://github.com/jopohl/urh/wiki/Supported-devices

**Comment by ZeroChaos-** [comment]
CLOSED: WORKSFORME

thanks!
