### ISSUE TITLE
Network interface (Socket) as SDR

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#28]
- [x] Add network plugin which can be used as alternative input in sniff dialog
- [x] network plugin options: socket, target address/port, listening (address/)port, ...
- [x] network plugin creates new button for send [next to save below table] via TCP in generator.
   - [x] Wait pauses when sending via TCP
- [ ] network plugin creates new device in sending dialog (for sending modulated data via TCP).
- [x] make encoding enforceable in generator via right click menu

**Comment by jopohl** [comment]
Problems:
- Load pcap: No informations about decoding/sample_rate.
- PCAP-Device: From which devices comes received data?

Suggestion: Simply add "Export to pcap" functionality.
