### ISSUE TITLE
how can i change the theme to black

### ISSUE THREAD

**Issue by robellebor** [jopohl/urh#295]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Platform Specifications

  - Python Version:
  - Operating System:
  - Version of URH:

**Comment by jopohl** [comment]
Go through ``` Edit ->  Options -> View -> Combobox at bottom -> fallback theme (dark) ``` and restart the application.

**Comment by robellebor** [comment]
thank you

**Comment by jopohl** [comment]
You're welcome!
