### ISSUE TITLE
Trouble with FSK

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#301]
[test1.cfile.gz](https://github.com/jopohl/urh/files/1126356/test1.cfile.gz)
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
In inspectrum i can see the transitions in FSK file

## Actual Behavior
In URH i can not see the transitions of the signal and am unable to make a proper decode.

## Platform Specifications

  - Python Version: 3
  - Operating System: Kali
  - Version of URH: latest from git

**Comment by jopohl** [comment]
The signal has very sharp edges in the normal view and does not look like a smooth sine wave:
![image](https://user-images.githubusercontent.com/18219846/27897737-5dadebd2-6222-11e7-8015-95c45fb63757.png)

There are two things that you could try here:
1. Recapture the signal with a higher sample rate
2. Double check the center frequency, you may be a bit off

If that should not work let me know!

**Comment by vsboost** [comment]
I will take a recapture for sure, i was just intrigued that inspectrum was able to display it.

**Comment by vsboost** [comment]
![screenshot from 2017-07-06 16-21-39](https://user-images.githubusercontent.com/11001973/27898055-59c72cdc-6267-11e7-9be7-f560fccff829.png)

**Comment by vsboost** [comment]
![screenshot from 2017-07-06 16-25-25](https://user-images.githubusercontent.com/11001973/27898165-f9466ff2-6267-11e7-9887-32fe40faad2a.png)

**Comment by jopohl** [comment]
That is indeed pretty impressive! You got an idea how inspectrum achieves this behind the scenes?

**Comment by vsboost** [comment]
Wish i knew...

**Comment by vsboost** [comment]
Think it makes use of liquiddsp

**Comment by andynoack** [comment]
This issue is maybe related to #264. We will have a deeper look on it after Blackhat.

**Comment by vsboost** [comment]
Cool.

**Comment by jopohl** [comment]
Hey @vsboost ,
you may be interested in the new spectrogram feature of URH. I just loaded your signal and selected the desired frequency band. Then I applied a bandpass filter via context menu with a filter bandwidth of 0,001 giving me this demodulated signal:
![bildschirmfoto_2017-08-24_17-21-33](https://user-images.githubusercontent.com/18219846/29673869-bf00153c-88f0-11e7-86a4-fc91966652a8.png)

**Comment by vsboost** [comment]
Sweet.  Thanks for your hard work with this project.

**Comment by michiuovidiu07** [comment]
Seara buna, am și eu o nelămurire, legat de acest subiect

**Comment by michiuovidiu07** [comment]
Good evening, I also have a question about this subject

**Comment by michiuovidiu07** [comment]
Please help me
