### ISSUE TITLE
Hard to verify FSK analysis / spectrum view missing

### ISSUE THREAD

**Issue by viraptor** [jopohl/urh#316]
There's not a great way to make sure how the parameters actually translate to the result in FSK mode.

With just the signal view, it's hard to check if the centre shift is right. It's also hard to see the number of samples per bit. The demodulated view helps a little, but doesn't give the whole picture.

Ideally, I'd like to switch to a spectrum view and see a line for the centre shift and a grid for sample/bit count.

**Comment by jopohl** [comment]
Let me give you an example how to find these parameters with URH. I will use this FSK modulated signal:

![fsk1](https://user-images.githubusercontent.com/18219846/28995140-1f601b80-79e1-11e7-831b-330ad517edb8.png)

I now switch to the demodulated view, to fine tune the parameters:

![bildschirmfoto_2017-08-05_13-16-53](https://user-images.githubusercontent.com/18219846/28995152-44a4fae6-79e1-11e7-8753-8fc78839c61c.png)

As you see, I selected a pulse and the number of selected samples is shown below the signal. This is an easy way to manually determine the bit length, if the auto detection did not work properly.

Furthermore, you see the center here indicated by the colored lower/upper area. Increasing the Y scale using the slider on the right might help here if you find it hard to see a thing in demodulated view.

Let me know what you think about this! It may also help, if you upload your signal so we can have a look at it.
