### ISSUE TITLE
Enabling of devices

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#320]
Enabled devices

## Actual Behavior
RTL-SDR / HackRF / SDRPlay are grayed out

What is the procedure to have the above devices enabled in the windows version of URH

## Platform Specifications

  - Python Version: 3
  - Operating System: Windows 8
  - Version of URH: 1.8

**Comment by jopohl** [comment]
The dlls for the mentioned devices were updated for the windows version, so maybe you need to reinstall using
```
pip uninstall urh
pip install urh --no-cache-dir
```

If that should not help, you can also try reinstalling with the new ``` msi ``` installer for windows: https://github.com/jopohl/urh/releases/download/v1.8.0/Universal.Radio.Hacker-1.8.0-amd64.msi

**Comment by jopohl** [comment]
Just had a deeper look on this, and I think I found the error -- might be other SDR software that interferes URH. I just fixed this in #321 and additionally added a health check button for native extenions to options. Could you pull latest master and see if it is fixed for you?

**Comment by vsboost** [comment]
Cool, ill give this a go on my work computer Monday and report back.

**Comment by vsboost** [comment]
Tested latest and can confirm it is working, thank you.
