### ISSUE TITLE
Spectrogram crashes in windows

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#323]
## Actual Behavior
Spectrogram crashes URH

## Steps to Reproduce the Problem

Open signal
Select Spectrogram

## Platform Specifications

  - Python Version: 3.6.1
  - Operating System: Windows 8.1
  - Version of URH: 1.8.4
  - URH was installed: MSI

![image](https://user-images.githubusercontent.com/11001973/29800492-b795e108-8cad-11e7-810f-5844516b1d7a.png)

**Comment by jopohl** [comment]
Can you upload the signal that produced this crash?

**Comment by vsboost** [comment]
[RTL-SDR-433_920MHz-2MSps-2MHz.zip](https://github.com/jopohl/urh/files/1262032/RTL-SDR-433_920MHz-2MSps-2MHz.zip)

This one has no signals of interest in it but still crashes URH when spectogram is selected.

**Comment by jopohl** [comment]
Thanks for the signal @vsboost that helped me to track down the error. Interestingly enough it only crashed on windows so I did not notice it when developing on linux. Should work now on latest master.

**Comment by vsboost** [comment]
Thanks
