### ISSUE TITLE
Decode CCITT #5

### ISSUE THREAD

**Issue by gustavecha** [jopohl/urh#328]
Hi all,

i've got signals using CCITT #5 tones.
https://www.sigidwiki.com/wiki/CCITT

Is there a way to decode them with URH please ?

All the best

**Comment by andynoack** [comment]
Currently URH only supports two different frequencies within a FSK. If you have a Signal with more than 1 Bit information per symbol, URH will not be able to decode it in the right way. Can you tell us about the devices you are investigating? Until now we have not had a use case for that, hence no support.

**Comment by gustavecha** [comment]
CCITT #5 tones are used to select a relay in professional trunked radio networks.
Let's say it's often used as a kind of phone number in cleartext and then, messages using different modulations (at higher baud rates for instance) follow up such tones.

URH won't be able to decode all messages, obviously, but it can be really interesting to know which number is used prior to go any further

**Comment by andynoack** [comment]
Sounds interesting! Do you have a small sample for us?

**Comment by andynoack** [comment]
I will close here, reopen (with sample file :) if you like!
