### ISSUE TITLE
Create signal from frequency selection (Spectrogram)

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#344]
Create signal from frequency selection is not working as expected.

Selecting the top fsk signal and creating signal from selection displays both top and bottom signal.
![image](https://user-images.githubusercontent.com/11001973/31986310-bf24db4e-b9b3-11e7-9690-014a8ea1b87b.png)
Selecting the middle fsk signal and creating signal from selection displays only middle signal (good).
![image](https://user-images.githubusercontent.com/11001973/31986347-dd660d12-b9b3-11e7-9d44-93ccdd363561.png)
Selecting the bottom fsk signal and creating signal from selection displays no signal.
![image](https://user-images.githubusercontent.com/11001973/31986363-ed73c19a-b9b3-11e7-89dc-f5998c1cd8df.png)
Have played around with the bandwidth settings but it does not help.

Windows version.
Universal Radio Hacker
Version: 1.8.10

**Comment by jopohl** [comment]
Could you please upload a sample of  your signal so we can have a deeper look?

**Comment by vsboost** [comment]
[HackRF-433_920MHz-2MSps-2MHzCopy.zip](https://github.com/jopohl/urh/files/1413871/HackRF-433_920MHz-2MSps-2MHzCopy.zip)

**Comment by vsboost** [comment]
Thanks, brickwall filter works a treat.

**Comment by jopohl** [comment]
Update on this: I fixed the default bandpass filter in a20ddb1d33c9c7e7d7a369cec90ff71af4587281 so it can also handle negative frequencies. Brickwall Filter may get removed soon due to bad performance.

**Comment by vsboost** [comment]
No probs, look forward to testing it out.
