### ISSUE TITLE
Substitution

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#348]
Hi there,

Here is what i have: 100000100000100010001000100000100010001000100000
Data is either 100000 or 1000

I was trying to use substitution to convert 100000 to 1 and 1000 to 0 but this does not work, unless i'm not using it correctly.
![image](https://user-images.githubusercontent.com/11001973/32132496-8f0fca54-bc10-11e7-9021-f2be8dd7340d.png)

Is there any other way you recommend having this data converted as it would make fuzzing much easier if you only deal with 1's or 0's that are really 100000 or 1000

Hope this makes sense.

**Comment by andynoack** [comment]
Hey @vsboost,
I think, you can solve that by:
1.) Invert
2.) Morse Code (3,4,1)
Does that help you?

**Comment by vsboost** [comment]
Yes this works.. Thanks for that.
