### ISSUE TITLE
Add possibility to set a minimum lenght for a message

### ISSUE THREAD

**Issue by inode-** [jopohl/urh#352]
During my tests I saw that the software is not able to manage the 0 at the end of the message in case of ASK demodulation. For example if our message is 100100101010101100 the software will interprete this as: 1001001010101011.

I didn't find any way to force the software to set a minimum lenght of a message that should be interpreted.

**Comment by jopohl** [comment]
Could you upload a signal that has this behaviour?

**Comment by vsboost** [comment]
I have come across this as well, would be nice to set a minimal message length so if the signal ends with a 1 to add the necessary amount of 0's to complete the message.

**Comment by inode-** [comment]
You can download a sample here: https://mega.nz/#!ncN0mb4Q!h4aGhHtdqHxELCvYCDgM9lSlV8--VxAzRqx0HY-rxN0 the modulation is OOK (an ASK with trasmission or no trasmission) with PWM encoding, 100 = 1, 110 = 0

**Comment by jopohl** [comment]
I hear you guys,  that would greatly simplify the demodulation of such signals. Will take care of it soon.
