### ISSUE TITLE
Enhance csv import

### ISSUE THREAD

**Issue by jopohl** [jopohl/urh#355]
Based on the discussion in #349 enhance the csv import in the following ways:
- [x] show an import wizard with preview of first columns and let users choose which column to use as  I-data 
- [x] Q data is always zero for oscilloscopes, so choosing Q data should be optional in the wizard
- [x] If timestamp column is given and selected, calculate sample rate from timestamps

**Comment by shumtravi** [comment]
Please add field "Sample rate". Now importer works fine with files with timestamps, but not so clear how it works when sample rate  already presented in header without timestamp column (With DScope-like files). May be you can made that field automatically calculated when timestamp column presented and manually editable if it not presented?

**Comment by jopohl** [comment]
I wrote that in the tooltip for the timestamp column: You can manually edit the sample rate in the signal details after import. The signal details can be opened with this button:

![bildschirmfoto_2017-11-18_09-38-58](https://user-images.githubusercontent.com/18219846/32978540-806859a0-cc44-11e7-97f3-f740703c3cda.png)

Does this work for you, or is it crucial to have a sample rate fiel in the CSV dialog?

**Comment by shumtravi** [comment]
Oh, now i see, it works, thank you. I think with sample rate field it will looks just more clear, but it not so crucial for me. Anyway your new csv-wizard looks good.
