### ISSUE TITLE
Exit immediately after launch.

### ISSUE THREAD

**Issue by GreenSlime** [jopohl/urh#358]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
Open URH

## Actual Behavior
URH process begins, then exits before opening a window

Previous version was removed prior to installing.
Filtered Procmon .PML logfire attached.
## Platform Specifications

  - Python Version: 3.6
  - Operating System: W10
  - Version of URH: 1.8.11 x64

[Logfile.zip](https://github.com/jopohl/urh/files/1476595/Logfile.zip)

**Comment by jopohl** [comment]
Could this be related to #356 ? A remove and reinstall did the trick here.

**Comment by GreenSlime** [comment]
I Used the ms installer, I had seen that post, and tried a clean install after removing all traces of old manually. Same result.

**Comment by jopohl** [comment]
Please try new version (1.8.12). This should work.

**Comment by GreenSlime** [comment]
Yep, program launches as expected now, top job.
Have encountered another issue now though regarding loading samples 'unpack requires a bytes object of length..)
I will open another issue for this.
