### ISSUE TITLE
Error opening sample: Unpack requires a bytes object of length

### ISSUE THREAD

**Issue by GreenSlime** [jopohl/urh#359]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behaviour
open .wav file

## Actual Behaviour
Errors out, image of dialogue added to post.

## Steps to Reproduce the Problem

  1. open URH
  2. Open file *.wav
  3.

## Platform Specifications

  - Python Version: 3.6
  - Operating System: Win 10 x64
  - Version of URH: 1.8.12
  - URH was installed:  MSI x64
![capture](https://user-images.githubusercontent.com/447126/32902706-02701696-caeb-11e7-994f-cda6824bee56.PNG)

Most likely an issue with my environment, a few clues on what to investigate would be useful.

**Comment by jopohl** [comment]
Only single channel wavs are supported, which may cause this error. This is documented [in the wiki](https://github.com/jopohl/urh/wiki/Supported-signal-file-formats).

Is it possible for you do recapture the signal and save it as ``` .complex ``` from URH or from the application you created the ``` .wav ``` ?

**Comment by GreenSlime** [comment]
File was produced with SDR#, stripping a channel off the sample still produces the same error, but I imagine I need to change my approach rather than improvise. 
I will use URH to gather the sample instead. A pity, as the signal I am monitoring is very sporadic, and SDR# made it convenient to monitor the frequency and gather a sample.
It looks like I would be better with GQRX perhaps.

Thank you for your advice

**Comment by jopohl** [comment]
Could you provide me with sample of your .wav file? I might add an import for SDR# created wavs.

**Comment by jopohl** [comment]
I just updated the file open routine for WAV files so it should be no problem anymore to open a WAV file from SDR#.
