### ISSUE TITLE
Bandpass filter error

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#370]
## Steps to Reproduce the Problem

Open signal
Change to Spectrogram view
Select signal
Apply bandpass filter

![image](https://user-images.githubusercontent.com/11001973/33428574-73b0fe32-d61d-11e7-849b-4978c528f913.png)

Clicking ok continues the process and works.

## Platform Specifications

  - Python Version:
  - Operating System: Windows 10
  - Version of URH: 1.8.15
  - URH was installed: ``.msi`

**Comment by jopohl** [comment]
Thanks for bringing this up. This problem only appears when using the ``` .msi ``` version on windows, so my unittests could not catch it. :wink: 

I just released [version 1.8.16](https://github.com/jopohl/urh/releases/tag/v1.8.16) which adresses this issue.

**Comment by vsboost** [comment]
Awesome, thanks again for your hard work.
