### ISSUE TITLE
TypeError under Win10//HackRf

### ISSUE THREAD

**Issue by mitkoge** [jopohl/urh#379]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
I press "Record signal" in "Sniff Protocol" and it should record data.

## Actual Behavior
Does not record.
(urh) C:\wsp\w_python\urh>urh
Will not regenerate UI, because script can't be found. This is okay in release.
Win32; Microsoft Visual C++ version 14.0; Boost_105900; UHD_003.010.001.001-release

[INFO::SettingsProxy.py::get_receive_buffer_size] Initializing receive buffer with size 400,000MB
[INFO::Device.py::start_rx_mode] HackRF: Starting RX Mode
[INFO::Device.py::log_retcode] HackRF-SETUP: Success
[INFO::Device.py::log_retcode] HackRF-SET_FREQUENCY to 433920000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_SAMPLE_RATE to 2000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_BANDWIDTH to 2000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_RF_GAIN to 0: Success
[INFO::Device.py::log_retcode] HackRF-SET_IF_GAIN to 16: Success
[INFO::Device.py::log_retcode] HackRF-SET_BB_GAIN to 30: Success
Process Process-1:
Traceback (most recent call last):
  File "c:\users\mitko\appdata\local\programs\python\python36\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\users\mitko\appdata\local\programs\python\python36\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\mitko\envs\urh\lib\site-packages\urh\dev\native\Device.py", line 137, in device_receive
    cls.enter_async_receive_mode(data_connection, ctrl_connection)
  File "c:\users\mitko\envs\urh\lib\site-packages\urh\dev\native\HackRF.py", line 47, in enter_async_receive_mode
    ctrl_connection.send_bytes("Start RX MODE:", str(ret))
  File "c:\users\mitko\appdata\local\programs\python\python36\Lib\multiprocessing\connection.py", line 185, in send_bytes
    m = memoryview(buf)
TypeError: memoryview: a bytes-like object is required, not 'str'

## Steps to Reproduce the Problem

  1. install urh under win10 using pip3
  2. start urh
  3. try to sniff using hackrf. (sdrsharp works perfect with hackrf)

## Platform Specifications

  - Python Version: 3.6
  - Operating System: win10
  - Version of URH: 1.9.0
  - URH was installed:  __via pip__

**Comment by jopohl** [comment]
Thanks for bringing this up. I could verify this issue and just released version [1.9.1](https://github.com/jopohl/urh/releases/tag/v1.9.1) to fix it.
