### ISSUE TITLE
Can't start 1.9.1 Windows 10

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#381]
Removed 1.9.0 and installed 1.9.1 and get.

![image](https://user-images.githubusercontent.com/11001973/34143237-cdff48e6-e4df-11e7-9744-6f75ba2a07d9.png)

Reverted back to 1.9.0 and working
.msi windows 10

**Comment by jopohl** [comment]
Can't reproduce. Does it work when you make a full uninstallation (i.e. uninstall 1.9.0 and then remove the Universal Radio Hacker folder) before installing 1.9.1?

**Comment by vsboost** [comment]
Uninstalled 1.9.0 and removed folder, installed 1.9.1 and working.

Cheers
