### ISSUE TITLE
Delete from Analysis Tab

### ISSUE THREAD

**Issue by muhantu** [jopohl/urh#388]
In URH, we can delete signal from interpretation tab, but can we delete just from analysis tab (per cell(s))?

In analysis tab, we only can hide rows, no delete per row or column.. 
Or I just missed that out??

**Comment by jopohl** [comment]
You have two ways to do that:
1. Select the bits you want to delete -> right click -> ``` Show selection in Interpretation ```. Here you can delete the corresponding part of the original signal. This is the preferred way to delete trash.
2. Right click anywhere on Analysis table and click on context menu ``` Writeable (decouples from signal) ```. Then you can delete bits using the Delete key inside the table.

**Comment by muhantu** [comment]
1. I know that, and usually use that..
2. I have try that, but that's mean interpretation and analysis is separate?

**Comment by muhantu** [comment]
Ok, I think `Writeable` solve my problem.. I can check and uncheck that..
Thanks @jopohl :D

**Comment by jopohl** [comment]
You're welcome. :)
