### ISSUE TITLE
HackRF One 125KHz, is possible?

### ISSUE THREAD

**Issue by lucapgt** [jopohl/urh#396]
Hi,
How I can receive 125KHz with HackRF One? Actually the lower frequency in URH with HackRF One is 1MHz, but the hardware can receive 125KHz without any problem.
Can you fix this? Can I modify some setup by myself (with your instructions)?

Thanks

**Comment by jopohl** [comment]
Hi @lucapgt ,
these limits are defined in ``` urh/src/urh/dev/config.py:26 ```. So if you checkout the source you could easily change it for yourself.

When setting the limits I was referring to [HackRFs Documentation](https://github.com/mossmann/hackrf/wiki/HackRF-One#features) where 1MHz is given as minimum frequency.

**Comment by lucapgt** [comment]
ok, it works fine. Thanks!
