### ISSUE TITLE
Undefined symbol for LimeSDR plugin

### ISSUE THREAD

**Issue by neeocf** [jopohl/urh#397]
hi,
as of commit https://github.com/myriadrf/LimeSuite/commit/c02f4358b6eb3a83f333e8951419f34b18667dde#diff-5938db8bef05ad9111fcc1199f87025b LimeSuite has deleted LMS_Disconnect() and LMS_IsOpen() functions, so urh has to probably be updated with latest LimeSuite.h header (and rebuild files generated by CPython, get rid of these API calls, and so on)..

**Comment by jopohl** [comment]
Thanks as lot for bringing this up. I made the required changes, so it should work again.
