### ISSUE TITLE
Feature Request: Byte order

### ISSUE THREAD

**Issue by cyko69** [jopohl/urh#420]
It would help if I could choose the byte order for every message field.

**Comment by jopohl** [comment]
Could you explain your use case a bit more?

You can already 
  1. choose the byte order in label view to change it for certain labels at the bottom of analysis
   ![screenshot_20180405_111321](https://user-images.githubusercontent.com/18219846/38357398-cf251d54-38c2-11e8-8570-e92954306567.png)
  2. choose "Change Bitorder" in decoding to apply it for all messages.
   ![screenshot_20180405_111542](https://user-images.githubusercontent.com/18219846/38357414-d97a5008-38c2-11e8-9cdb-cb9aaa03dae3.png)

**Comment by cyko69** [comment]
Was on vaccation, so sorry for the late answer.
Both options are changing the BIT order, i need to have a different BYTE order (endianess).
e.g. I got a 0111110000000001 (0x7c 0x01) and i need to interpret this as ‭000101111100‬ (0x01 0x7c),
so the decimal value i want to have is (dec) 380 (and not 31745).

**Comment by jopohl** [comment]
Ah thanks for the clarification. So we are talking about a new Column "endianess" next to "Bit order" in the label table at the bottom?
