### ISSUE TITLE
add external decoder 'urh-ETH_Comfort_decode_plugin' to wiki page

### ISSUE THREAD

**Issue by nospam2000** [jopohl/urh#424]
please add the external decoder 'urh-ETH_Comfort_decode_plugin' to the table of the wiki page 'External decodings'.

Use the following line:
`|  eQ-3/ELV/Technoline ETH comfort | [GitHub Repo](https://github.com/nospam2000/urh-ETH_Comfort_decode_plugin) | [nospam2000](https://github.com/nospam2000)
`

**Comment by jopohl** [comment]
Done. Thanks for sharing!
