### ISSUE TITLE
Checksum calculation wrong

### ISSUE THREAD

**Issue by sycophantic** [jopohl/urh#438]
## Expected Behavior
Calculate correct checksum using polynomial 31.
a1a502cb0819080003d0020000 should have checksum 28. See [CRC8/MAXIM](http://crccalc.com/?crc=a1%20a5%2002%20cb%2008%2019%2008%2000%2003%20d0%2002%2000%2000&method=crc8&datatype=hex).

## Actual Behavior
Checksum calculation is wrong.
Checksum calculated is 6a, see screenshot.

![screenshot from 2018-05-21 23-11-28](https://user-images.githubusercontent.com/634076/40340483-1c70d5d6-5d4d-11e8-8099-511f88d1becf.png)

## Platform Specifications

  - Python Version: 3.6.5
  - Operating System: Ubuntu 18.04
  - Version of URH: 2.0.4
  - URH was installed: via pip

**Comment by andynoack** [comment]
Actually the computation of the CRC is not wrong but you need two parameters (RefIn=true and RefOut=true -> input and output bits are inverted/reflected) to calculate it in your way. We are about to implement these, stay tuned :)

**Comment by sycophantic** [comment]
Great. Thanks!
