### ISSUE TITLE
Question: is it possible to decode this in your sw? (similar to differential manchester)

### ISSUE THREAD

**Issue by Nesos-ita** [jopohl/urh#455]
I don't like the idea of asking questions here, as it is a place to post issues, but you can always close this as "not issue, ask to google/duckduckgo"  
I have this signal (rf thermometer, but also tv IR) where:
 - 001 means 1 (because of long signal+ignore/skip the next)  
 - 01 means 0 (because is short+skip next)  
is similar to differential manchester, in fact: no transition means 1, tansition means 0.  
bit if i use that it throw many errors because there is never 11, only 00.  
![this](https://user-images.githubusercontent.com/20688006/40958183-a09e9004-6898-11e8-9f25-0cef089aa9a9.png)  
if it is not possible i'll do it by sw, and maybe also the generation.  
example using differential manchester in sw:  
00101 decodes to 10 in sw (+1decoding error) (ok)  
001001 decodes to 10 in sw (+2decoding error) (i want this to be 11)

**Comment by jopohl** [comment]
Did you try to create a new decoding with a substiution table like this?
![bildschirmfoto_2018-06-05_08-29-39](https://user-images.githubusercontent.com/18219846/40958739-aa58dcba-689a-11e8-9b45-9b76f8777915.png)

**Comment by andynoack** [comment]
Maybe you are looking for a custom decoding like "Invert, Morse Code (1,2,1)"

**Comment by Nesos-ita** [comment]
Substitution doesn't work, it's also in the description "use only same length".  
but invert+morse code is exactly what i was looking for!  
i applied that decoding, all the labels, and this program it's just AWESOME!!!

**Comment by andynoack** [comment]
You can only have one decoding per line. For special purposes, however, you can exclude arbitrary labels from applying that selected encoding of the line (Do Not Decode flag).
