### ISSUE TITLE
LimeMlni

### ISSUE THREAD

**Issue by carlolucarini** [jopohl/urh#459]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
Expected to see "LimeSDR" in the "Device:" select menu.

## Actual Behavior
"LimeSDR" not present.

## Steps to Reproduce the Problem
Open urh from command line

## Platform Specifications

  - Python Version: 3
  - Operating System: Ubuntu 16.04LTS
  - Version of URH: 2.1.0
  - URH was installed: via pip__

**Comment by jopohl** [comment]
Did you enable LimeSDR in Edit -> Options -> Device?

**Comment by carlolucarini** [comment]
I went into the optional section, but the system tells me that "Device supports neither sending nor receiving" and the Limesdr is disabled

**Comment by carlolucarini** [comment]
limesdr -- ERROR: No module named 'urh.dev.native.lib.limesdr'

**Comment by jopohl** [comment]
Did you install limesdr package and created the symlink to the ```.so``` as described [here](https://github.com/jopohl/urh#generic-way-with-pip-ubuntudebian)?

**Comment by andynoack** [comment]
If the problem persists, feel free to comment below. We will reopen it in that case.

**Comment by carlolucarini** [comment]
Hi, I'm looking for some information to better configure SdmLime with the Lime SuiteGui. I do not have radio frequency skills, I'm studying the RollJam system for my work. I am an Italian police investigator, is it possible to have a private email to talk about our project ???-------- Messaggio originale --------Oggetto: Re: [jopohl/urh] LimeMlni (#459)Da: "Prof. Dr. Andreas Noack" A: jopohl/urh CC: carlolucarini ,Author Closed #459.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/jopohl/urh/issues/459#event-1681013201","url":"https://github.com/jopohl/urh/issues/459#event-1681013201","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jopohl/urh","title":"jopohl/urh","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jopohl/urh"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #459."}],"action":{"name":"View Issue","url":"https://github.com/jopohl/urh/issues/459#event-1681013201"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jopohl/urh] LimeMlni (#459)",
"sections": [
{
"text": "",
"activityTitle": "**Prof. Dr. Andreas Noack**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@andynoack",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jopohl/urh/issues/459#event-1681013201"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 344641292\n}"
}
],
"themeColor": "26292E"
}

**Comment by andynoack** [comment]
I recommend joining our slack channel for discussions as there are many researchers and students that also may help you. In case it is confidential you can also reach us by mail.

**Comment by carlolucarini** [comment]
It would be better to be able to talk in a confidential manner, alternatively if you have a contact it would be welcome to take a break.

**Comment by andynoack** [comment]
There are private channels in slack, If you like to join. Otherwise you can mail us via {andreas.noack, johannes.pohl}@hochschule-stralsund.de

**Comment by carlolucarini** [comment]
OK thanks
