### ISSUE TITLE
Feather Request (?): Save received to data hex file.

### ISSUE THREAD

**Issue by anthropic-radio-source** [jopohl/urh#487]
Hi all

Feature request (?)

I am fairly new to URH but think it is a marvelous tool. I have looked but cannot find any easy way to save the bit/hex/ascii data to a separate file for analysis by other tools. Currently, I cut/past the data from either the Interpretation or Analysis widow and save to a text file. Unfortunately, this is saved as in ASCII and need a bit of furtling to get it into a hex file.

Is there any way I can save it straight to a hex format file?

Regards

ARS

**Comment by anthropic-radio-source** [comment]
Sorry title should read Feature Request (?): Save received data to data hex file.

Spell checker was too quick for me.

**Comment by jopohl** [comment]
Thanks for your request, this is indeed not possible right now, but should be quite easy to add. We will have a look at it!

**Comment by anthropic-radio-source** [comment]
Thanks. It will save me loads of time.
