### ISSUE TITLE
not support bladerf x40?

### ISSUE THREAD

**Issue by wooyunvip** [jopohl/urh#495]
in kali linux#dmesg:
[  766.216117] usb 1-1: USB disconnect, device number 4
[ 2481.315248] usb 1-1: new high-speed USB device number 5 using ehci-pci
[ 2481.673171] usb 1-1: New USB device found, idVendor=1d50, idProduct=6066
[ 2481.673172] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2481.673173] usb 1-1: Product: bladeRF
[ 2481.673174] usb 1-1: Manufacturer: Nuand
[ 2481.673174] usb 1-1: SerialNumber: 45e18975b4759838990679c9baba9e07
already install libbaderf-dev
and do python3 main.py
show devices:
<img src="https://i.loli.net/2018/07/11/5b45b54d5e261.jpg">

**Comment by jopohl** [comment]
There is no native support for BladeRF: https://github.com/jopohl/urh/wiki/Supported-devices

If you provide us with a test device we might add support but till then you need to use the GNU Radio backend for BladeRF.
