### ISSUE TITLE
GFSK modulation support for generator

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#5]
- [x] Implement GFSK algorithm
- [x] Show in Modulator GUI (new combox entry)
- [x] allow adjusting bt and filter length in GUI via spinboxes

**Comment by jopohl** [comment]
Adapt the phase is needed to prevent spiky jumps and correct the fact, that we sample discrete points
sin(2*pi*f_1*t_1 + phi_1) = sin(2*pi*f_2*t_1 + phi_2)
<=> phi_2 = 2*pi*t_1*(f_1 - f_2) + phi_1
