### ISSUE TITLE
2.2.3 not on PyPI

### ISSUE THREAD

**Issue by ilovezfs** [jopohl/urh#515]
did upload to PyPI fail?

**Comment by jopohl** [comment]
Yes indeed. They now enforce a required e-mail address or else the upload will fail with:
```
HTTPError: 400 Client Error: User 'jopohl' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
```

Just verified my e-mail and reuploaded it. Thanks for bringing this up!

**Comment by ilovezfs** [comment]
You're welcome @jopohl! Voilà https://github.com/Homebrew/homebrew-core/pull/30569
