### ISSUE TITLE
how do i start this after install

### ISSUE THREAD

**Issue by jamieduk** [jopohl/urh#526]
## Expected Behavior
dont know how to use or launch app ?

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Platform Specifications

  - Python Version:
  - Operating System:
  - Version of URH:
  - URH was installed: __from source__ /// __via pip__ /// via ```.msi```

**Comment by jopohl** [comment]
Simply open a terminal, type ``` urh ``` and hit enter.
