### ISSUE TITLE
RFE: Support multiple devices of the same type (Specifically rtl-sdr)

### ISSUE THREAD

**Issue by larsks** [jopohl/urh#529]
I have multiple RTL-SDR dongles attached to my system. I would like to be able to specify which one urh should use.  At the moment, urh does not provide any mechanism for selecting a specific rtl-sdr device. If another program is using the "first" dongle, urh is unable to use a different device.

**Comment by jopohl** [comment]
Are you using the latest version of URH? If so, you should be able to choose a RTL-SDR using a device identifier:

![grafik](https://user-images.githubusercontent.com/18219846/45297473-ca66d180-b505-11e8-8bcc-0635174038b9.png)

Once you have multiple RTL-SDRs attached, simply hit the green refresh button and you will be able to choose an identifier from the dropdown menu.

**Comment by larsks** [comment]
My bad, I wasn't using the latest version. Sorry for the noise!
