### ISSUE TITLE
Add device support for CC1101

### ISSUE THREAD

**Issue by y0d4a** [jopohl/urh#540]
with this lib.? 
https://github.com/veonik/arduino-cc1101

tnx.

**Comment by jopohl** [comment]
What do you want to do with it? CC1101 encoding is already built-in and accessible in decoding dialog.

**Comment by y0d4a** [comment]
well, to use him as transceiver? 
because is cheap and freq. range is great for experimenting ...

**Comment by jopohl** [comment]
Ah you mean, you want device support added?

**Comment by y0d4a** [comment]
yes, sorry for misunderstanding :)

**Comment by jopohl** [comment]
No problem, just adapted the title for a bit more clarity. :)

**Comment by y0d4a** [comment]
thank you :)

here is one more lib if you need, also for rspi:
https://github.com/SpaceTeddy/CC1101

and cheap module:
https://www.aliexpress.com/item/CC1101-Wireless-RF-Transceiver-315-433-868-915MHZ-SMA-Antenna-Wireless-Module-1-8-3-6V/32858137093.html?spm=a2g0s.9042311.0.0.4f594c4dTuYQ9t

**Comment by dartrax** [comment]
I would love to see that, too! 👍

**Comment by Bihel29** [comment]
I would also like the CC1101 module to be compatible with URH as a transmitter for replay attack.


Thanks jopohl

**Comment by FFY00** [comment]
There are actually some modules that have a cc1101 and a USB serial interface, having support for those would also be great!

Example: https://www.aliexpress.com/item/433Mhz-CC1101-USB-Wireless-RF-Transceiver-Module-10mW-USB-UART-MAX232-RS232-CF/32675590009.html?spm=2114.search0104.3.8.64632d99GqtNnB&ws_ab_test=searchweb0_0,searchweb201602_8_10065_10068_319_10059_10884_317_10887_10696_321_322_453_10084_454_10083_10103_10618_10304_10307_10820_10301_10821_537_536_10902,searchweb201603_45,ppcSwitch_0&algo_expid=1d552150-a7d5-463a-b657-58d321083953-1&algo_pvid=1d552150-a7d5-463a-b657-58d321083953

**Comment by xixuedafa** [comment]
wanted  Yard Stick ONE  :）
