### ISSUE TITLE
DC Correction?

### ISSUE THREAD

**Issue by bluegizmo83** [jopohl/urh#551]
Would it be possible to add DC Correction to this program? When using a HackRF, the center DC spike makes it very difficult to capture a clean signal with Universal Radio Hacker...

**Comment by jopohl** [comment]
Sure, nice idea! Would you need it live during recording or would it suffice as a new operation in Interpretation?

**Comment by bluegizmo83** [comment]
Thanks! I'm thinking live during recording would be best.
