### ISSUE TITLE
Error start v2.4.0

### ISSUE THREAD

**Issue by bluegizmo83** [jopohl/urh#553]
I'm getting this error on run after installing v2.4.0 (previous version I was using was working fine, which I think was v2.2.4)
![urherror](https://user-images.githubusercontent.com/1000998/47237963-d4e67780-d39d-11e8-9807-f098ff935b4c.jpg)

**Comment by jopohl** [comment]
Thanks for bringing this up. Just rebuild the ``` .msi ``` installers and it should work now. I currently have no Windows VM to test, so could you please redownload version v2.4.0 and tell me, if it works?

**Comment by bluegizmo83** [comment]
Just retested with the rebuilt .msi installer, it's working fine now, thanks!

**Comment by jopohl** [comment]
Awesome! You're welcome!
