### ISSUE TITLE
Strong signal

### ISSUE THREAD

**Issue by ratay** [jopohl/urh#560]
##### Is your feature request related to a problem?

I'm trying to investigate traffic from several devices through RTL-SDL USB dongle
problem is that some of them are nearly my equipment and signal is too strong
signal wave is truncated even if I decrease gain to 0

##### Describe the solution you'd like

Is it possible to enable negative values in gain ?

##### Describe alternatives you've considered

I tried to reproduce situation in command line:
`urh_cli.exe -v -d RTL-SDR -di 0 -f 868930000 -s 1000000 -b 20000 -g -4 -rx -db native  -a -mo FSK -bl 10 -n 0.2 -file out.dat
`

but I got an error:
```
[INFO::SettingsProxy.py::get_receive_buffer_size] Try to allocate receive buffer with size 400.000MB
[INFO::Device.py::start_rx_mode] RTLSDR: Starting RX Mode
Receiving for 3.0 seconds...
Found Fitipower FC0012 tuner
[INFO::Device.py::log_retcode] RTLSDR-OPEN (#0): Success
Exact sample rate is: 1000000.026491 Hz
[INFO::Device.py::log_retcode] RTLSDR-SET_FREQUENCY to 868930000.0: Success
[INFO::Device.py::log_retcode] RTLSDR-SET_SAMPLE_RATE to 1000000.0: Success
[INFO::Device.py::log_retcode] RTLSDR-SET_BANDWIDTH to 20000.0: Success
[ERROR::Device.py::log_retcode] **RTLSDR-SET_FREQUENCY_CORRECTION to 0: Error Code: -2 (-2)**
Disabled direct sampling mode
[INFO::Device.py::log_retcode] RTLSDR-SET_DIRECT_SAMPLING_MODE to 0: Success
[INFO::Device.py::log_retcode] RTLSDR-SET_RF_GAIN to -40: Success
[INFO::Device.py::log_retcode] RTLSDR-RESET_BUFFER: Success

Stopping receiving...
[INFO::Device.py::stop_rx_mode] RTLSDR: Stopping RX Mode: Stopping receiving due to user interaction
[INFO::Device.py::log_retcode] RTLSDR-CLOSE: Success
[INFO::Device.py::read_device_messages] Exiting read device message thread due to
[INFO::Device.py::read_receiving_queue] EOF Error: Ending receive thread
Received data written to out.dat
```
same error is triggered from GUI when frequency correction is set to "0"
but default value in GUI is "1" - when all works correctly
I not found this setting in urh_cli

##### Additional context

using latest version of URH on Windows 7 x64

**Comment by jopohl** [comment]
In the log you posted there is the line
```
[INFO::Device.py::log_retcode] RTLSDR-SET_RF_GAIN to -40: Success
```
so regarding gain everything seemed to work fine. 

The setting for ``` Frequency Correction``` is indeed missing for CLI I can add that, no problem.
I will also enable negative gains in UI. Thanks for bringing this up!
