### ISSUE TITLE
Simple Receiver and Sender Module Support 

### ISSUE THREAD

**Issue by l0nax** [jopohl/urh#562]
Is there a possibility to use [these](https://www.amazon.de/dp/B071J2Z3YK/ref=cm_sw_em_r_mt_dp_U_bXz2BbNAADQWG) Receiver and Sender Module?

**Comment by andynoack** [comment]
Hey @l0nax,

the devices look great, but these are no SDRs. Therefore, there might be support like for the Yard-Stick (TX only). Actually you have the possibility to control them with the RPi over the hardware interface, so we do not see a motivation to add further support through URH as you (normally) wouldn't pentest signals with URH on a RPi (RAM...). Do we miss anything?

Best
Andreas

**Comment by l0nax** [comment]
Okay, thanks :)
