### ISSUE TITLE
Program automatically executes on Windows startup

### ISSUE THREAD

**Issue by cjastone** [jopohl/urh#568]
##### Expected Behavior
Universal Radio Hacker does not automatically start with Windows.

##### Actual Behavior
Universal Radio Hacker starts with Windows.  Have verified this behavior on 2 machines.

##### Steps To Reproduce
Install product and reboot machine.

##### Screenshots
![image](https://user-images.githubusercontent.com/20256822/48466659-9926bc80-e83a-11e8-849c-505bfdc3574c.png)

##### Platform Specifications

 - OS: Windows 10 1803
 - URH version: 2.4.2
 - Installed via MSI

**Comment by underwoodblog** [comment]
I don't like the autostart feature to. It's enabled with every update again. Does it under Windows 7 to!
