### ISSUE TITLE
Issues with USRP B200

### ISSUE THREAD

**Issue by jopohl** [jopohl/urh#608]
There seem to be problems with native support for USRP B200 on Windows #589 and OSX #577. Since we do not have a USRP B200 for testing, we need some help. I see two options:

1. Someone in contact with Ettus can arrange getting a test device for us.
2. Someone with a USRP B series device helps us with debugging.

**Comment by robisen1** [comment]
I have a USRP B series device and would be happy to help. How can I contribute?

**Comment by jopohl** [comment]
Thank you @robisen1 ! 

The best way to start is to look at ``` tests/device/TestUSRP.py ``` and change line 20 to 
```
return_code = usrp.open("type=b200")
```
so it explicitly uses the B series for testing or to  
```
return_code = usrp.open("")
```
for automatic detection of attached USRPs.
 
-----

After that, attach your USRP and run the test e.g. from command line with 

``` 
python -m unittest tests/device/TestUSRP.py 
```

For first we need to find out where exactly the crash happens. Please post the __complete log/stacktrace__ for the test. Please also tell me what __OS__ you are using. Ideally you could test it under Linux, Windows and OS X but any help is appreciated. :+1:

**Comment by robisen1** [comment]
I am using the MSI version for Windows but I am fine with running it on Ubuntu or any other OS you would recommend. Would Ubuntu be better for this?

Thanks,

Robi 
On 3/12/2019 11:51:06 PM, Johannes Pohl <notifications@github.com> wrote:
Thank you @robisen1 [https://github.com/robisen1] !
The best way to start is to look at tests/device/TestUSRP.py and change line 20 to
return_code = usrp.open("type=b200")
so it explicitly uses the B series for testing or to
return_code = usrp.open("")
for automatic detection of attached USRPs.
After that, attach your USRP and run the test e.g. from command line with
python -m unittest tests/device/TestUSRP.py
For first we need to find out where exactly the crash happens. Please post the complete log/stacktrace for the test. Please also tell me what OS you are using. Ideally you could test it under Linux, Windows and OS X but any help is appreciated. 👍

**Comment by jopohl** [comment]
Ideally you would test it on Ubuntu (or any other linux distribution you prefer), since things are a bit easier to debug there. If we found the problem there we can verify if it works on your Windows machine too.

**Comment by robisen1** [comment]
will do

**Comment by robisen1** [comment]
Sorry this took so long but I did install this on Ubuntu 18.04 and updated
the testUSRP.py. I tried both the type=b200 and the " " approaches and each
threw errors. It says it cannot the library usrp. I have installed
libuhd-dev

thoughts?


[image: Screenshot from 2019-03-30 22-43-54.png]

**Comment by jopohl** [comment]
You need to build the device extensions by calling:

```
python src/urh/cythonext/build.py 
```

**Comment by robisen1** [comment]
will do latter today. thanks. I was thinking that i need to build the uhd from source.

**Comment by robisen1** [comment]
I have everything now working. One thing I need to do before running the
build script was

sudo python3 /usr/lib/uhd/utils/uhd_images_downloader.py

btw I ran "python src/urh/cythonext/build.py" but it gave a error and said
run "/usr/lib/x86_64-linux-gnu/uhd/utils/uhd_images_downloader.py"" but
that file does not live there. it resides at "
/usr/lib/uhd/utils/uhd_images_downloader.py"

here is the b200 running on URH. BTW thanks and I hope this helps others.
[image: Screenshot from 2019-03-31 15-04-51.png]

**Comment by jopohl** [comment]
The screenshot is not visible so what exactly do you mean by it is running on URH? Is the unit test passing or does it work in spectrum analyzer / record dialog?

**Comment by robisen1** [comment]
Its passes all tests. I can see signals with Spectrum Analyzer, I can
record signals, etc.

**Comment by jopohl** [comment]
Very cool, thanks for your support so far! Any chance you can test it under Windows and/or OS X too? The issues #589 and #577 indicate errors on these systems.

**Comment by robisen1** [comment]
I have a windows system. I can look at it on there. I dont think I have a
OSX system any more but I'll look.

**Comment by jopohl** [comment]
Any news?

**Comment by robisen1** [comment]
I apologize for not doing this sooner. I attempted to install using pip in
python on two systems but keep getting a this error

"    running build_ext
    Finalizing options
    building 'urh.cythonext.auto_interpretation' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\urh
    creating build\temp.win-amd64-3.6\Release\src\urh\cythonext
    C:\Anaconda2\envs\pyten36\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall
-DMS_WIN64 -Ic:\anaconda2\envs\pyten36\include
-Ic:\anaconda2\envs\pyten36\include
-Ic:\anaconda2\envs\pyten36\lib\site-packages\numpy\core\include -c
src/urh/cythonext/auto_interpretation.cpp -o
build\temp.win-amd64-3.6\Release\src\urh\cythonext\auto_interpretation.o
/openmp
    gcc: error: /openmp: No such file or directory
    error: command
'C:\\Anaconda2\\envs\\pyten36\\Library\\mingw-w64\\bin\\gcc.exe' failed
with exit status 1"

should i use the MSI instead?

**Comment by jopohl** [comment]
The MSI will be harder to debug, so it would be better if we get the source build up and running.

Did you install a C compiler on your system? It seems to look for mingw gcc. You could install Visual Studio Community with the bundled C++ Compiler which I know works for URH on Windows.

**Comment by robisen1** [comment]
i have VSS installed and MINGW. Ill look to see if there is a path issue

**Comment by robisen1** [comment]
Got it installed. I need to force Anacdona to use the right mingw comipler
version byt installing it in the virtual environment, then setting the
path, then doing a pip install urh.

It starts up. I went to look to see if the file structure was the same as
Linux but it seems different. I don't see a tests folder

**Comment by jopohl** [comment]
It is better to do a git clone of the repositoriy than to install it with Anacondas pip. Then you will have the same file structure as on Linux. You can basically use the same instructions from my post near the top for this.

**Comment by robisen1** [comment]
Ok. I'll try that.

**Comment by robisen1** [comment]
I just wanted to say I have not dropped this. I ran into some compilation
issues which are a configuration issue on my side. Hopefully I'll have time
tomorrow to resolve that.

**Comment by jopohl** [comment]
Any news so far? From what I can tell you verified it is working on Ubuntu. Since there there are no OS specific changes from URH side when using native USRP backend I assume the error source for reported problems is not in URH.

I will close here. If someone has more information just drop a comment and I can reopen it.
