### ISSUE TITLE
Filter file types in dir

### ISSUE THREAD

**Issue by lunakk-PL** [jopohl/urh#611]
##### Expected Behavior
displaying previously saved files in protocol dir

##### Actual Behavior
list is empty
##### Steps To Reproduce

1. Go to 'Save protocol as'
2. when saving file type marked as "(*proto.xml *.proto)" is selected previously saved files in dir are invisible
3. after changing file type to "All files (*)" files are showing correctly in directory

##### Screenshots
![bug](https://user-images.githubusercontent.com/45714159/51382843-270f7400-1b18-11e9-80f0-77826f141a47.png)

##### Platform Specifications
OS: Windows 10 x64 ver. 10.0.17134
URH version: 2.5.4
Python version: 3.7.2
Installed via msi

**Comment by andynoack** [comment]
The filter is for files ending with *.proto.xml or *.proto, __not__ only *.xml!

**Comment by lunakk-PL** [comment]
I understand, thx.
BTW great software :)
