### ISSUE TITLE
Edit -> Decoding->External Program-> Decoder, Encoder File Chooser grayed out.

### ISSUE THREAD

**Issue by Jackfritt** [jopohl/urh#619]
##### Expected Behavior
Encoder and Decoder scripts should be chooseable

##### Actual Behavior
Button "..." for Decoder and Decoder are greyed out. Nothing happpens on Mouseclick

##### Steps To Reproduce

1. Go to 'Edit'
2. Click on 'Decoding'
3. Choose 'External Program'
4. Try to click on Decoder "..." Button or Encoder "..." Button both are greyed out.

##### Platform Specifications

 - OS: [Debian 9.7]
 - URH version: [e.g. 2.5.5]
 - Python version: [e.g. 3.5]
 - Installed via [e.g. pip]

**Comment by jopohl** [comment]
Did you drag and drop the "External Program" primitive into the decoding chain?

![grafik](https://user-images.githubusercontent.com/18219846/53147165-fdc68580-35a6-11e9-9e8a-fdfde82ca197.png)

**Comment by Jackfritt** [comment]
Thx for that hint. Workes like a charm. Fastest support ever.
