### ISSUE TITLE
Not working BPSK with 'Bit Lenght' = 280

### ISSUE THREAD

**Issue by ywg20190410** [jopohl/urh#641]
Good Day!
Please, help me!
I try interpretation WAV-file with recorded BPSK modulated signal.
When I set  'Bit Lenght' = 280 interpretation not working?
Why?
![image](https://user-images.githubusercontent.com/49470819/55856678-70ee8000-5b84-11e9-9a0f-c3326f4bd8d4.png)
![image](https://user-images.githubusercontent.com/49470819/55856746-a85d2c80-5b84-11e9-870c-594c26fe3e6f.png)
![image](https://user-images.githubusercontent.com/49470819/55856760-b57a1b80-5b84-11e9-92da-4b1f75535099.png)

Thank You!

**Comment by andynoack** [comment]
Hey @ywg20190410 ,
please join us on Slack (invite link is noted in readme) as this is not an issue in URH.
Best Andreas
