### ISSUE TITLE
Segmentation fault  can't select hackRF 

### ISSUE THREAD

**Issue by mayday77** [jopohl/urh#651]
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 2 leaked semaphores to clean up at shutdown
  len(cache))
Segmentation fault

**Comment by mayday77** [comment]
Linux parrot 4.19.0-parrot4-28t-amd64 #1 SMP Parrot 4.19.28-2parrot4.28t (2019-04-18) x86_64 GNU/Linux

**Comment by jopohl** [comment]
1. Please use the issue template.
2. Please post a complete log.
3. Did you follow the install instructions?
