### ISSUE TITLE
Wishlist: Support for constellation diagram

### ISSUE THREAD

**Issue by pointhi** [jopohl/urh#658]
##### Is your feature request related to a problem?

Finding out how a signal is modulated.

##### Describe the solution you'd like

Add support for [Constellation diagrams](https://en.wikipedia.org/wiki/Constellation_diagram) which allows to figure out the modulation scheme quite easily. (at least from what I know about RF)

##### Additional context

![](https://image.slidesharecdn.com/digitalmodulationtechniques-120429100215-phpapp01/95/digital-modulation-techniques-15-1024.jpg)

![](https://slideplayer.com/slide/12412504/74/images/75/100G+constellation+diagrams%E2%80%A6.jpg)

**Comment by andynoack** [comment]
Hi @pointhi,

we have discussed implementing a constellation diagram, but do not see a real benefit. In practice most constellation diagrams of loaded or recorded signals would be just a ring without characteristic points. Considering the required effort for implementation we do not think that it makes sense in URH. If you have good arguments for practical usage, drop us a message.

Best 
Andreas and Johannes
