### ISSUE TITLE
not sending with hackrf on urh

### ISSUE THREAD

**Issue by mrudde** [jopohl/urh#664]
Can anyone help?

I have record a wireless signal from a switch, via hackrf on urh.

But when i will transmit this on the same frequenz and settings, nothing will send. 
I have test it with an openelec sdr on gqrx. 

 - OS: Debian
![signal on gqrx from remote control](https://user-images.githubusercontent.com/13756332/59873577-9a096900-939c-11e9-96e8-2cdf88cd787e.png)
![test send from hackrf so same frequenz](https://user-images.githubusercontent.com/13756332/59873578-9aa1ff80-939c-11e9-8900-c625c30003d1.png)

**Comment by jopohl** [comment]
Try to increase the gain (TX and/or RX).

**Comment by jopohl** [comment]
I am closing here, if you still need help our slack channel is a better place to discuss this problem.

**Comment by careyer** [comment]
likely have the same problem here #905
