### ISSUE TITLE
Pause threshold isn't respected in Interpretation window

### ISSUE THREAD

**Issue by sshawuk** [jopohl/urh#681]
##### Expected Behavior
![issue](https://user-images.githubusercontent.com/7057604/63045980-66911980-bec9-11e9-847d-d44ee947c965.png)

With a pause threshold of 8 bits, I expect the signal displayed in the above screenshot to be split at the 8 zero bits highlighted (amongst other repetitions of 8 zero bits).

##### Actual Behavior

The messages run together into one long message, ignoring the expected 8 bit pauses. 

##### Steps To Reproduce
1. Load a file for analysis. 
2. Automatically detect, and adjust parameters. 
3. Confirm that for this ASK signal, a pause threshold of 8 bits is set. 
4. Confirm that the signal does include 8 consecutive zero bits 

##### Platform Specifications

 - OS: Ubuntu
 - URH version: 2.7.3
 - Python version: 3.6.8
 - Installed via pip

**Comment by jopohl** [comment]
Did you try 7?

**Comment by sshawuk** [comment]
I did. It doesn't break this signal apart no matter how low I drop the threshold.

**Comment by jopohl** [comment]
Can you copy your bits to a .txt file and upload it here so I can have a look?

**Comment by sshawuk** [comment]
Sure thing, here you go :)

[sample_no_pause_detection.zip](https://github.com/jopohl/urh/files/3502931/sample_no_pause_detection.zip)

p.s. Really appreciate your attention. URH is a fantastic program!

**Comment by jopohl** [comment]
Just had a look at your signal. Pause threshold refers to pause bits only (=bits coming from ranges in noise area). So an easy fix for your signal is to set the Noise threshold to "0.1412" and Pause Threshold to 7:

![grafik](https://user-images.githubusercontent.com/18219846/63050394-daaecb80-be8f-11e9-9b40-3d5e31ef8f23.png)

**Comment by sshawuk** [comment]
Thank you!

I totally misunderstood exactly what constituted a pause bit! Really appreciate your help! Keep up the amazing work!
