### ISSUE TITLE
Add Repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [jopohl/urh#687]
### Summary
A way for users to see what downstream repositories carry urh

### Proposed design
The full badge looks like so:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/urh.svg?header=urh)](https://repology.org/project/urh/versions)  

but since it take up a lot of room it can be simply added as a single badge such as:

[![Packaging status](https://repology.org/badge/tiny-repos/urh.svg)](https://repology.org/project/urh/versions)

**Comment by jopohl** [comment]
Added it. Very cool idea thanks for the suggestion!
