### ISSUE TITLE
Reverse DoorBell Signal [HELP WANTED]

### ISSUE THREAD

**Issue by nocomp** [jopohl/urh#689]
hi johannes, hi folks, 
i ve followed all your videos on how reverse a signal, but it seems that is not enough for me :/
replay of the signal doesn t work, i was wondering if somebody would be kind enough to give me a hand on mentoring the reversing with me.
all files are captures (captured with usrp), i can get team viewer runing, ready to paypal the course if needed.
i just need to to be able to get it done propelly.
i can also keep this topic open in order to put all details here in order to be usefull for others
thank you for your time

**Comment by andynoack** [comment]
Hi @nocomp, 
our Slack channel #urh might be the right place to get support! I will close this issue because we like to separate technical issues from mentoring.
Best Andreas
