### ISSUE TITLE
Slack invite link in readme has expired

### ISSUE THREAD

**Issue by mcauser** [jopohl/urh#691]
Slack invite link in readme has expired.

https://stralsundsecurity.slack.com/join/shared_invite/enQtMjEwOTIxNzMzODc3LWU4ZWIzMTQ3NDAyNjkzODBhZTJiZDNmN2U0MTA4ZTM1MjhhNTNiYTc4YzQ5MDk2NjU5YzMxOWJmMDQyZDczYjg
> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

**Comment by andynoack** [comment]
There you go :)

https://join.slack.com/t/stralsundsecurity/shared_invite/enQtMjEwOTIxNzMzODc3LTk3NmE4MGVjYjEyYTMzYTdmN2RlNzUzYzg0NTNjNTQ2ODBkMzI3MDZlOWY3MjE4YjBkNTM4ZjJlNTJlZmJhNDg
