### ISSUE TITLE
rtlsdr OSX not working

### ISSUE THREAD

**Issue by sfuthings** [jopohl/urh#692]
I have installed rtlsdr, tested with rtl_test and OSX detected it.
Using URH binaries version 2.7.5, URH failed to start rtlsdr with error

RTLSDR-OPEN (#0): Error Code: -99 (-99)
RTLSDR: failed to start rx mode

EDIT: hackrf does not work as well, but both do work in GQRX.

**Comment by jopohl** [comment]
I assume you are running OSX < 10.14 as your issue sounds the same like in #690. So either upgrade your OS or use pip3 or brew to install URH.
