### ISSUE TITLE
Universal.Radio.Hacker-2.8.0-x64.exe failing to start

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#694]
##### Expected Behavior
Program to start

##### Actual Behavior
Program does not start

##### Steps To Reproduce
Download file
Install
Run

##### Platform Specifications
Windows 10

Just updated as usual and program does not load, uninstalled and reinstalled and same issue, noticed the new release is ~19Mb as opposed to ~44Mb for previous.

**Comment by jopohl** [comment]
Thanks for testing this so fast! Seems like the CI is in weekend too and therefore produced a corrupted ``` .exe ```. :wink: 

I just replaced it with a proper one and verified it is running in a Windows VM.

**Comment by vsboost** [comment]
All good now, thanks for the new version..
