### ISSUE TITLE
OverflowError: value too large to convert to uint16_t when recording signals in URH

### ISSUE THREAD

**Issue by rnui2k** [jopohl/urh#699]
##### Expected Behavior
Record a signal within URH and load it into the Interpretation tab

##### Actual Behavior
After recording the signal (> 10 seconds), when saving the capture URH crashes. 
Haven't experience crashes with captures less than 10(ish) seconds. After the crash, when trying to reload the saved file, URH generates an error dialog box. 

##### Steps To Reproduce

On Debian Testing 5.2.17-1, Linux Kernel 5.2.0-3-amd64, Python 3.7.5 
1. From terminal, run urh ('urh' + Enter)
2. Click File
3. Click Record Signal
4. Set Frequency to 432.0 MHz 
5. Set device to Hackrf
6. Set Sample rate to 8.0M
7. Click Start
8. Record signal for >10 Seconds
9. Click Stop
10. Click Save
11. Navigate to directory
12. Remain file to arbitrary name (i.e. 'Button-Press-6-Times.complex16s')
13. Click Save in Dialog Box
14. Experience Crash
##### Crash output from Terminal
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[INFO::SettingsProxy.py::get_receive_buffer_size] Allocate receive buffer with 6.667GB
[INFO::Device.py::start_rx_mode] HackRF: Starting RX Mode
[INFO::Device.py::log_retcode] HackRF-SETUP: Success
[INFO::Device.py::log_retcode] HackRF-SET_FREQUENCY to 433920000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_SAMPLE_RATE to 10000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_BANDWIDTH to 10000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_RF_GAIN to 0: Success
[INFO::Device.py::log_retcode] HackRF-SET_IF_GAIN to 16: Success
[INFO::Device.py::log_retcode] HackRF-SET_BB_GAIN to 14: Success
[INFO::Device.py::log_retcode] HackRF-Start RX MODE: Success
[INFO::Device.py::stop_rx_mode] HackRF: Stopping RX Mode: Stopped receiving: Stop button clicked
[INFO::Device.py::log_retcode] HackRF-STOP RX MODE: Success
[INFO::Device.py::log_retcode] HackRF-CLOSE: Success
[INFO::Device.py::log_retcode] HackRF-EXIT: Success
[INFO::Device.py::read_receiving_queue] EOF Error: Ending receive thread
[DEBUG::Device.py::read_receiving_queue] Exiting read_receive_queue thread.
[INFO::Device.py::read_device_messages] Exiting read device message thread due to 
[DEBUG::Device.py::read_device_messages] Exiting read device errors thread
[INFO::Device.py::start_rx_mode] HackRF: Starting RX Mode
[INFO::Device.py::log_retcode] HackRF-SETUP: Success
[INFO::Device.py::log_retcode] HackRF-SET_FREQUENCY to 432000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_SAMPLE_RATE to 8000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_BANDWIDTH to 8000000.0: Success
[INFO::Device.py::log_retcode] HackRF-SET_RF_GAIN to 0: Success
[INFO::Device.py::log_retcode] HackRF-SET_IF_GAIN to 16: Success
[INFO::Device.py::log_retcode] HackRF-SET_BB_GAIN to 14: Success
[INFO::Device.py::log_retcode] HackRF-Start RX MODE: Success
[INFO::Device.py::stop_rx_mode] HackRF: Stopping RX Mode: Stopped receiving: Stop button clicked
[INFO::Device.py::log_retcode] HackRF-STOP RX MODE: Success
[INFO::Device.py::log_retcode] HackRF-CLOSE: Success
[INFO::Device.py::log_retcode] HackRF-EXIT: Success
[INFO::Device.py::read_device_messages] Exiting read device message thread due to 
[DEBUG::Device.py::read_device_messages] Exiting read device errors thread
[INFO::Device.py::read_receiving_queue] EOF Error: Ending receive thread
[DEBUG::Device.py::read_receiving_queue] Exiting read_receive_queue thread.
[DEBUG::Device.py::stop_rx_mode] Closing parent control connection: handle is closed
[INFO::Device.py::stop_rx_mode] HackRF: Stopping RX Mode: Dialog closed. Killing recording process.
[DEBUG::SendRecvDialog.py::closeEvent] Device stopped successfully.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/controller/MainController.py", line 722, in on_signals_recorded
    self.add_signalfile(filename, enforce_sample_rate=sample_rate)
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/controller/MainController.py", line 290, in add_signalfile
    self.add_signal(signal, group_id)
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/controller/MainController.py", line 311, in add_signal
    sig_frame.refresh(draw_full_signal=True)  # protocol is derived here
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/controller/widgets/SignalFrame.py", line 1175, in refresh
    self.show_protocol(refresh=True)
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/controller/widgets/SignalFrame.py", line 523, in show_protocol
    self.update_protocol()
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/controller/widgets/SignalFrame.py", line 510, in update_protocol
    self.proto_analyzer.get_protocol_from_signal()
  File "/usr/local/lib/python3.7/dist-packages/urh-2.8.1-py3.7-linux-x86_64.egg/urh/signalprocessing/ProtocolAnalyzer.py", line 229, in get_protocol_from_signal
    signal.bits_per_symbol, signal.center_spacing)
  File "src/urh/cythonext/signal_functions.pyx", line 364, in urh.cythonext.signal_functions.grab_pulse_lens
    str modulation_type, uint16_t samples_per_symbol,
OverflowError: value too large to convert to uint16_t
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 4 leaked semaphores to clean up at shutdown
  len(cache))
Aborted

Similar experiences on Arch Linux

##### Platform Specifications

 - OS: Debian Testing 5.2.17-1
 - URH version: 2.8.1
 - Python version: 3.7.5
 - Installed via Github and build

##### Additional Details
The files that crash URH are >100MB in size.

![image](https://user-images.githubusercontent.com/58123291/69486743-d4c86f00-0e1c-11ea-8399-ad9416222dc1.png)

**Comment by jopohl** [comment]
Does it work when you uncheck (in main menu bar): Edit -> Auto detect signals on loading?
