### ISSUE TITLE
Decoders location

### ISSUE THREAD

**Issue by nico0481** [jopohl/urh#706]
Hi,

Where are located user made decoders?(Those in the pick list with Mancherster I, Manchester II,....)
Is there a way to share those decoders between users?

Thank you

Best regards
Nico

**Comment by jopohl** [comment]
> Where are located user made decoders?

* If you have a project opened they are saved in the project file ``` URHProject.xml ``.
* Otherwise they are saved in ``` ~/.config/urh/decodings.txt ```

> Is there a way to share those decoders between users?

Sure, just copy the enitre files or directly copy/paste the desired decoding from the file. It is plain text format.

In future, use [our slack channel](https://join.slack.com/t/stralsundsecurity/shared_invite/enQtMjEwOTIxNzMzODc3LTk3NmE4MGVjYjEyYTMzYTdmN2RlNzUzYzg0NTNjNTQ2ODBkMzI3MDZlOWY3MjE4YjBkNTM4ZjJlNTJlZmJhNDg) for such questions, as this is not an issue.
