### ISSUE TITLE
Issue With LimeSDR Mini under Windows 

### ISSUE THREAD

**Issue by observator-x** [jopohl/urh#707]
##### Platform Specifications
 - OS: Windows 10

I have an issue with LimeSDR-Mini under Windows 10, Generator -> Send Signal

It is detected in the Device Identifier, but when sending a message it sends an non-modulated carrier once, after that i have to reset the device by pulling it out and push it in again to the USB slot, with other software under Windows and Ubuntu it works fine, and using latest firmware.

LimeSDR-Mini works fine with GNU radio, LimeSuiteGUI etc.

**Comment by jopohl** [comment]
Does it work with URH under Ubuntu?

**Comment by observator-x** [comment]
I will test this weekend with URH under ubuntu, have 2x Lime-SDR Mini so then will test them both.

**Comment by observator-x** [comment]
No issues using Ubuntu

**Comment by jopohl** [comment]
What version of LimeSuite is installed in your Ubuntu?

**Comment by observator-x** [comment]
Version: 19.04.1-ga5b3a10f
Build date: 2019-11-12

**Comment by jopohl** [comment]
Did you build that from source? The latest release on Github is 19.04 (https://github.com/myriadrf/LimeSuite/releases) and this version is bundled URH on windows. You might try to compile this 19.04.1 version on windows and place the resulting DLL in the installation directory of URH to see if that makes a difference.

**Comment by observator-x** [comment]
Yes i built it from latest commit (wich is not the latest windows release)

**Comment by jopohl** [comment]
Is the latest release working for you? If not, it might be a good idea to open an issue at the limesuite repo.

**Comment by observator-x** [comment]
I dont have the latest release of limesuite.dll yet, i installed SDRangel because it uses this dll also but unfortunatly it was an older version too, i think to build the dll from source have to compile with visual studio first, which i dont had no time todo yet.

**Comment by jopohl** [comment]
Closing here due to inactivity.
