### ISSUE TITLE
Build urh.dev.native.lib.hackrf on Windows

### ISSUE THREAD

**Issue by Wei1234c** [jopohl/urh#715]
Thank you for this great package. 

I am using Windows and would like to wrap urh.dev.native.lib.hackrf for my project. However, urh.dev.native.lib.hackrf was not built.

On Linux we can `install libhackrf-dev` and then `pip install urh` to build urh.dev.native.lib.hackrf, how do I do so on Windows? Please give me some hints.  Thanks!

**Comment by jopohl** [comment]
This is not an issue with URH but with your local development environment. I can't give support for that. If you want to install URH on windows use the native windows installer or install it via pip (it works on Windows too).
