### ISSUE TITLE
868 Mhz bug ???

### ISSUE THREAD

**Issue by rserroyen** [jopohl/urh#716]
Hello
I use the Universal Radio Hacke and it works well but in the band 868,250 I cannot detect usable frames then the rtl_433 works well!
Why
thank you so much

`Test mode active. Reading samples from file: Test868.cu8
Input format: uint8
Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3254                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [25;27]        ( 104 us)
 [ 2] count:    5,  width:    50 [42;53]        ( 200 us)
 [ 3] count:    2,  width:    78 [78;78]        ( 312 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [25;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;79]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    7,  width:   115 [104;131]      ( 460 us)
 [ 2] count:    6,  width:    78 [78;79]        ( 312 us)
 [ 3] count:    1,  width:   156 [156;156]      ( 624 us)
Level estimates [high, low]:  15955,     22
Frequency offsets [F1, F2]:    4387,  -7520     (+16.7 kHz, -28.7 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 26, long_limit: 26, reset_limit: 26624, demod_arg: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {125} 21 55 55 55 55 55 55 54 5b a9 31 0a 30 b5 27 58

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3255                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [26;27]        ( 104 us)
 [ 2] count:    5,  width:    50 [42;52]        ( 200 us)
 [ 3] count:    2,  width:    78 [78;78]        ( 312 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [26;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;78]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    7,  width:   115 [104;131]      ( 460 us)
 [ 2] count:    6,  width:    78 [78;79]        ( 312 us)
 [ 3] count:    1,  width:   157 [157;157]      ( 628 us)
Level estimates [high, low]:  15892,     25
Frequency offsets [F1, F2]:    3478,  -7561     (+13.3 kHz, -28.8 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 26, long_limit: 26, reset_limit: 26624, demod_arg: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {125} 21 55 55 55 55 55 55 54 5b a9 31 0a 30 b5 27 58

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3252                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [25;27]        ( 104 us)
 [ 2] count:    4,  width:    52 [52;53]        ( 208 us)
 [ 3] count:    2,  width:    78 [78;79]        ( 312 us)
 [ 4] count:    1,  width:    40 [40;40]        ( 160 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [26;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;78]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    4,  width:   137 [130;157]      ( 548 us)
 [ 2] count:    4,  width:   104 [104;105]      ( 416 us)
 [ 3] count:    6,  width:    78 [78;79]        ( 312 us)
Level estimates [high, low]:  15994,     12
Frequency offsets [F1, F2]:    3443,  -8756     (+13.1 kHz, -33.4 kHz)
Guessing modulation: No clue...

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3254                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [25;27]        ( 104 us)
 [ 2] count:    4,  width:    52 [52;53]        ( 208 us)
 [ 3] count:    2,  width:    78 [78;78]        ( 312 us)
 [ 4] count:    1,  width:    41 [41;41]        ( 164 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [25;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;79]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    7,  width:   115 [104;131]      ( 460 us)
 [ 2] count:    6,  width:    78 [78;78]        ( 312 us)
 [ 3] count:    1,  width:   157 [157;157]      ( 628 us)
Level estimates [high, low]:  15994,     14
Frequency offsets [F1, F2]:    4501,  -8000     (+17.2 kHz, -30.5 kHz)
Guessing modulation: No clue...

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3254                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [25;27]        ( 104 us)
 [ 2] count:    5,  width:    50 [42;53]        ( 200 us)
 [ 3] count:    2,  width:    78 [78;79]        ( 312 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [26;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;78]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    4,  width:   137 [130;157]      ( 548 us)
 [ 2] count:    4,  width:   104 [104;105]      ( 416 us)
 [ 3] count:    6,  width:    78 [78;79]        ( 312 us)
Level estimates [high, low]:  15938,     11
Frequency offsets [F1, F2]:    3126,  -8350     (+11.9 kHz, -31.9 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 26, long_limit: 26, reset_limit: 26624, demod_arg: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {125} 21 55 55 55 55 55 55 54 5b a9 31 0a 30 b5 27 58

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3255                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [26;27]        ( 104 us)
 [ 2] count:    5,  width:    50 [42;52]        ( 200 us)
 [ 3] count:    2,  width:    78 [78;79]        ( 312 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [26;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;78]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    7,  width:   115 [104;131]      ( 460 us)
 [ 2] count:    6,  width:    78 [78;79]        ( 312 us)
 [ 3] count:    1,  width:   157 [157;157]      ( 628 us)
Level estimates [high, low]:  15887,     12
Frequency offsets [F1, F2]:    3150,  -7361     (+12.0 kHz, -28.1 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 26, long_limit: 26, reset_limit: 26624, demod_arg: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {125} 21 55 55 55 55 55 55 54 5b a9 31 0a 30 b5 27 58

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3248                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [26;28]        ( 104 us)
 [ 2] count:    4,  width:    52 [52;52]        ( 208 us)
 [ 3] count:    2,  width:    78 [78;78]        ( 312 us)
 [ 4] count:    1,  width:    36 [36;36]        ( 144 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    3,  width:   103 [103;104]      ( 412 us)
 [ 2] count:   37,  width:    26 [26;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;79]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;53]        ( 208 us)
 [ 1] count:    7,  width:   115 [104;131]      ( 460 us)
 [ 2] count:    6,  width:    78 [78;79]        ( 312 us)
 [ 3] count:    1,  width:   156 [156;156]      ( 624 us)
Level estimates [high, low]:  15874,     21
Frequency offsets [F1, F2]:    3314,  -8528     (+12.6 kHz, -32.5 kHz)
Guessing modulation: No clue...

Detected FSK package
Analyzing pulses...
Total count:   49,  width:  3255                (13.0 ms)
Pulse width distribution:
 [ 0] count:    1,  width:     0 [ 0; 0]        (   0 us)
 [ 1] count:   41,  width:    26 [26;27]        ( 104 us)
 [ 2] count:    5,  width:    50 [42;52]        ( 200 us)
 [ 3] count:    2,  width:    78 [78;79]        ( 312 us)
Gap width distribution:
 [ 0] count:    5,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    3,  width:   104 [104;105]      ( 416 us)
 [ 2] count:   37,  width:    26 [26;27]        ( 104 us)
 [ 3] count:    3,  width:    78 [78;78]        ( 312 us)
Pulse period distribution:
 [ 0] count:   34,  width:    52 [52;54]        ( 208 us)
 [ 1] count:    7,  width:   115 [104;131]      ( 460 us)
 [ 2] count:    6,  width:    78 [78;79]        ( 312 us)
 [ 3] count:    1,  width:   157 [157;157]      ( 628 us)
Level estimates [high, low]:  15901,      7
Frequency offsets [F1, F2]:    3056,  -8473     (+11.7 kHz, -32.3 kHz)
Guessing modulation: Pulse Code Modulation (Not Return to Zero)
Attempting demodulation... short_limit: 26, long_limit: 26, reset_limit: 26624, demod_arg: 0
pulse_demod_pcm(): Analyzer Device
bitbuffer:: Number of rows: 1
[00] {125} 21 55 55 55 55 55 55 54 5b a9 31 0a 30 b5 27 58
![Capture1](https://user-images.githubusercontent.com/23522994/71989370-d796ec00-3231-11ea-978b-3adebd32e451.JPG)
![Capture2](https://user-images.githubusercontent.com/23522994/71989371-d796ec00-3231-11ea-9d5c-f552d223c8b8.JPG)
`
 - OS: window 10

**Comment by jopohl** [comment]
I think your gain is set too high. Nevertheless, there is a [slack channel](https://join.slack.com/t/stralsundsecurity/shared_invite/enQtMjEwOTIxNzMzODc3LTk3NmE4MGVjYjEyYTMzYTdmN2RlNzUzYzg0NTNjNTQ2ODBkMzI3MDZlOWY3MjE4YjBkNTM4ZjJlNTJlZmJhNDg) for that kind of questions.
