### ISSUE TITLE
Pulse Position Modulation (PPM) Modulation support?

### ISSUE THREAD

**Issue by sm0yyq** [jopohl/urh#728]
Hi.

I wonder if it is possible to add support for PPM Modulation as in ADS-B for example.?

**Comment by andynoack** [comment]
Hi, I think you can already realize a PPM demodulation using an advanced encoding. Have not tried it myself, but I think that you might do it with [invert] and [substitution] or [morse code].

**Comment by andynoack** [comment]
Closed due to inactivity, comment if it cannot be solved with encoding.
