### ISSUE TITLE
HackRF disabled and can't use it

### ISSUE THREAD

**Issue by All3xJ** [jopohl/urh#742]
##### Expected Behavior

I should be able to use HackRF with URH.

##### Actual Behavior
It is transparent in settings, so I can't enable it.

##### Steps To Reproduce

1. Go to Preferences
2. Click on Device
3. Can't enable HackRF

##### Screenshots

![Schermata 2020-03-07 alle 14 05 40](https://user-images.githubusercontent.com/20903913/76144111-4bf8da80-607d-11ea-84bd-d9546473ce14.png)
Also if I start urh with "sudo urh", it still displays the same error.

##### Platform Specifications

 - OS: [MacOS Catalina]
 - URH version: [2.8.3]
 - Python version: [2.7.16]
 - Installed via [pip]

I also have installed gr-osmosdr via brew.

**Comment by jopohl** [comment]
Why not use the DMG?

Am 7. März 2020 14:12:24 MEZ schrieb All3xJ <notifications@github.com>:
>##### Expected Behavior
>
>I should be able to use HackRF with URH.
>
>##### Actual Behavior
>It is transparent in settings, so I can't enable it.
>
>##### Steps To Reproduce
>
>1. Go to Preferences
>2. Click on Device
>3. Can't enable HackRF
>
>##### Screenshots
>
>![Schermata 2020-03-07 alle 14 05
>40](https://user-images.githubusercontent.com/20903913/76144111-4bf8da80-607d-11ea-84bd-d9546473ce14.png)
>
>
>##### Platform Specifications
>
> - OS: [MacOS Catalina]
> - URH version: [2.8.3]
> - Python version: [2.7.16]
> - Installed via [pip]
>
>I also have installed gr-osmosdr via brew.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jopohl/urh/issues/742

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by All3xJ** [comment]
> Why not use the DMG? Am 7. März 2020 14:12:24 MEZ schrieb All3xJ <notifications@github.com>:
> […](#)
> ##### Expected Behavior  I should be able to use HackRF with URH. ##### Actual Behavior It is transparent in settings, so I can't enable it. ##### Steps To Reproduce  1. Go to Preferences 2. Click on Device 3. Can't enable HackRF ##### Screenshots  ![Schermata 2020-03-07 alle 14 05 40](https://user-images.githubusercontent.com/20903913/76144111-4bf8da80-607d-11ea-84bd-d9546473ce14.png) ##### Platform Specifications  - OS: [MacOS Catalina] - URH version: [2.8.3] - Python version: [2.7.16] - Installed via [pip] I also have installed gr-osmosdr via brew. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #742
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by innerfirebg** [comment]
I have the same error but in Linux (parrot os). how can i resolve this?

**Comment by jopohl** [comment]
https://github.com/jopohl/urh#generic-installation-with-pip-ubuntudebian

**Comment by innerfirebg** [comment]
YES, I install it with pip and everything else and i have gnuradio too.... and my hackrf work with other tools

**Comment by jopohl** [comment]
libhackrf-dev installed?

**Comment by innerfirebg** [comment]
damn, that missing, thanks!
