### ISSUE TITLE
[BUG] Changes on "center" setting doesn't make any difference

### ISSUE THREAD

**Issue by All3xJ** [jopohl/urh#744]
##### Expected Behavior

When I edit the "center" value setting, nothing changes and I can't analyze the signal correctly.

##### Actual Behavior
Nothing changes.

##### Steps To Reproduce

1. Edit 'center' value
2. Nothing changes

##### Screenshots

![Schermata 2020-03-08 alle 15 01 31](https://user-images.githubusercontent.com/20903913/76164276-dd378200-614d-11ea-9645-053e224d7431.png)
![Schermata 2020-03-08 alle 15 01 48](https://user-images.githubusercontent.com/20903913/76164281-e3c5f980-614d-11ea-9873-741be9c75207.png)
![Schermata 2020-03-08 alle 15 02 22](https://user-images.githubusercontent.com/20903913/76164282-eaed0780-614d-11ea-93cd-41f928395f20.png)

##### Platform Specifications

 - OS: [MacOS Catalina]
 - URH version: [2.8.3]
 - Installed via [dmg]

**Comment by jopohl** [comment]
The center is visible in Signal View -> Demod.
Furthermore, your signal has a big DC component, so you should remove that with a DC filter.
