### ISSUE TITLE
LimeSDR mini

### ISSUE THREAD

**Issue by sgoudelis** [jopohl/urh#745]
I apologize if has been asked before. I saw too many issues about LimeSDR mini but none for the issue I am having.
When I try to record a signal, I do not see the LimeSDR option in the list of SDRs. I am on Ubuntu 19.10 and I am running urh 2.8.4 and I compiled LimeSDRSuite from source. 

I tried the same on Windows 10 and everything works fine.
Any ideas ?

**Comment by jopohl** [comment]
Edit -> Options -> Device and check "LimeSDR" there. If it is disable, use the "rebuild" button in this dialog. You may need to give the Include dir and the Lib dir there if it not directly works.

**Comment by sgoudelis** [comment]
Excellent! Everything works fine!
