### ISSUE TITLE
cu8 signal file not vertically centered

### ISSUE THREAD

**Issue by kroylar** [jopohl/urh#771]
##### Expected Behavior
When loading the attached b.cu8 file, the Analog signal path should be vertically centered on the plot, like shown in this quick plot of the same data using matplotlib:
![Figure_1](https://user-images.githubusercontent.com/1858370/80674082-bfa7da00-8a65-11ea-8c50-225dd443f6f8.png)

I believe it should be centered because the noise is actually centered at 128, which is half the 8-bit unsigned number representing it.

##### Actual Behavior
The path is instead placed in the lower half of the plot.
![2020-04-29-220008_799x470_scrot](https://user-images.githubusercontent.com/1858370/80673719-d1d54880-8a64-11ea-96ec-36bd542a6fd0.png)

##### Steps to Reproduce
1. Download the attached [b.cu8.log](https://github.com/jopohl/urh/files/4556226/b.cu8.log) file
2. Rename it to b.cu8
3. Open it in urh

##### Platform Specifications
 - OS: Arch Linux
 - URH version: 2.8.7
 - Python version: 3.8
 - Installed via AUR

**Comment by andynoack** [comment]
Your signal is not centered as you can see in the spectogram view in the upper area. You can select the shifted channel as shown and create a new signal from it (shown in the middle). Sometimes also the DC correction filter helps to center the signal, not in this case, however.

![Screenshot_20200430_103935](https://user-images.githubusercontent.com/18283204/80690395-0b429e00-8acf-11ea-9c15-50895cdc172f.png)
