### ISSUE TITLE
Default NRZi decoder configured incorrectly

### ISSUE THREAD

**Issue by hllhll** [jopohl/urh#775]
##### Expected Behavior
NRZ-i Decoder should perform NRZ-i (or NRZi) decoding, I.E. A change from x->!x is 1, else 0
 0100011110 should translate into
   110010001
##### Actual Behavior
Instead it just inverts the data (`Invert stock decoding`)

##### Additional info:
It seems that the stock software decoder for NRZi is configured as `invert` and not as `differential encoding`

**Comment by andynoack** [comment]
Thanks for the hint, i just fixed it!

**Comment by hllhll** [comment]
I Guess this is also another way to fix :)

While I'm here I must say this is an incredible piece of software, for my current project i'm using virtually ALL OF THE PROGRAM FEATURES! without writing single line of code.

**Comment by andynoack** [comment]
Yes, we discussed it internally and found several resources with different NRZ-I definitions. We think, it is the best solution to avoid the name NRZ-I to not confuse anyone.
