### ISSUE TITLE
Noisy signal

### ISSUE THREAD

**Issue by dwarning** [jopohl/urh#777]
Hello,
I like the concept of receiver integration for further signal analysis.
I tried to catch a signal at 434.5MHz / 115200Baud from a shutter remote control with my rtl-sdr stick.
I used actual URH at first windows 2.8.7 later with Ubuntu 2.8.8.
The problem is that the signal is very noisy in the demodulated signal view.
![Bildschirmfoto von 2020-05-21 14-20-00](https://user-images.githubusercontent.com/18441932/82560037-ee026c00-9b70-11ea-85fa-055ab05c1e91.png)
Here you see the analog signal on top and the demodulated below. The behavior is same also for different receive settings like gain, frequency shift from carrier or sampling rate. 
Also applying the moving averaging filter with different tap count is not successful. 
I made same signal catch with rtl_433 and converted to pulseview.
![Pulseview](https://user-images.githubusercontent.com/18441932/82560652-23f42000-9b72-11ea-9e4c-05b6af639e4e.gif)
Question is, how can I improve signal quality to get more stable decoding.

**Comment by andynoack** [comment]
Hey, that is rather a question for our Slack channel and not the issues. Short answer: Try to increase the sample rate and better record at 433,92M. I would like to move the question to Slack because it is about using URH, so i will close here.
