### ISSUE TITLE
Add support for baseband signal

### ISSUE THREAD

**Issue by mminnella** [jopohl/urh#795]
I would like to import the already demodulated data (via CSV file) into URH and the analyze it.
Actually I'm able to import this kind of data via CSV and it looks fine in the analog view, but then URH want to apply one of ASK /FSK /PSK before continue with the analysis phase
I've extracted these data via sigrok on the device before they are sent to the radio.
Anyway due the fact tha URH is great for analyzing bitstream it could be also used also for generic bitstream analysis.

Maybe adding a "Baseband" button along "ASK/FSK/PSK" in the modulation drop down list, with the related code could make the trick.

**Comment by jopohl** [comment]
Actually this is already supported. You just need to have your signal as a single channel wav file and load it into URH. Cheers!

Am 3. August 2020 18:49:40 MESZ schrieb Massimiliano Minnella <notifications@github.com>:
>I would like to import the already demodulated data (via CSV file) into
>URH and the analyze it.
>Actually I'm able to import this kind of data via CSV and it looks fine
>in the analog view, but then URH want to apply one of ASK /FSK /PSK
>before continue with the analysis phase
>I've extracted these data via sigrok on the device before they are sent
>to the radio.
>Anyway due the fact tha URH is great for analyzing bitstream it could
>be also used also for generic bitstream analysis.
>
>Maybe adding a "Baseband" button along "ASK/FSK/PSK" in the modulation
>drop down list, with the related code could make the trick.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jopohl/urh/issues/795

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mminnella** [comment]
Thank you for your support!
