### ISSUE TITLE
Snap / URH 2.8.8 BladeRF-OPEN / Error Code -7

### ISSUE THREAD

**Issue by Semnodime** [jopohl/urh#798]
##### Expected Behavior
Record from BladeRF

##### Actual Behavior
BladeRF-OPEN: Error Code: -7 (-7)
BladeRF: If you experience problems, make sure you place a rbf file matching your device at the correct location. See http://www.nuand.com/fpga_images/ and https://github.com/Nuand/bladeRF/wiki/FPGA-Autoloading
BladeRF: failed to start rx mode

##### Steps To Reproduce

1. Install snapd and bladerf on a fresh Linux Mint 20 x64 system
1. `bladeRF-cli -p` (without sudo!) should display the BladeRF device (else add udev rules and reload them)
1. Install URH via Snap
1.1 `snap install urh`
1.1 `sudo snap connect urh:raw-usb`
1. Launch urh GUI via shell command `/snap/bin/urh`
1.1 Click 'File' -> 'Record Signal...'
1.1 select `BladeRF` in DeviceSettings/Device
1.1 Press 'Start'
1. See error

##### Platform Specifications
 - OS: Linux Mint 20 x64
 - URH Version: 2.8.8
 - Python version: either Python 2.7.18rc1 or Python 3.8.2 (which is unknown due to snap)
 - Installed via 'snap install urh'

**Comment by jopohl** [comment]
Fixed in 2.8.9.
