### ISSUE TITLE
Windows detects Universal.Radio.Hacker-2.8.9-x86.exe as Zpevdo.B and Wacatac.D6!ml Trojoan 

### ISSUE THREAD

**Issue by JanikWie** [jopohl/urh#804]
Expected Behavior
Not getting this warning

Actual Behavior
See title

Steps To Reproduce
Download Universal.Radio.Hacker-2.8.9-x86.exe 
and scan it using windows Defender under windows 10 1909 

Screenshots
![IssueUhr](https://user-images.githubusercontent.com/37297366/94823653-61ac6380-0404-11eb-8cf4-4bef042b8468.jpg)

**Comment by jopohl** [comment]
This seems to be an issue with PyInstaller, let me quote the author here:
> Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

> If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

> See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

_Originally posted by @htgoebel in https://github.com/pyinstaller/pyinstaller/issues/4633#issuecomment-688886522_

Alternatively, you can install URH using pip or run it from source to avoid this warning.
