### ISSUE TITLE
Not Open on macOS Big Sur

### ISSUE THREAD

**Issue by brunohorta82** [jopohl/urh#818]
##### Expected Behavior
Try open application 

##### Actual Behavior
Not open on MacOS BigSur
##### Steps To Reproduce
Install and try open via DMG

**Comment by jopohl** [comment]
Confirmed. This is a known QT issue on Big Sur: https://bugreports.qt.io/browse/QTBUG-87014

As a workaround you need to set the environment variable ```QT_MAC_WANTS_LAYER``` to 1, e.g., with``` launchctl setenv QT_MAC_WANTS_LAYER 1 ``` before starting URH.

I will keep this issue open until a fixed QT version is available and make a new release then.

**Comment by jopohl** [comment]
Fixed in 2.9.0
