### ISSUE TITLE
rfcat not sending

### ISSUE THREAD

**Issue by BlessYou656** [jopohl/urh#845]
Hi,i have problem with send data via rfcat.Rfcat now use bytes instead of string to send data..Here is error:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/rflib/__init__.py in <module>
----> 1 d.RFxmit('\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\')

/usr/local/lib/python3.9/dist-packages/rflib/chipcon_nic.py in RFxmit(self, data, repeat, offset)
   1125         waitlen += repeat * (len(data) - offset)
   1126         wait = USB_TX_WAIT * ((old_div(waitlen, RF_MAX_TX_BLOCK)) + 1)
-> 1127         self.send(APP_NIC, NIC_XMIT, b"%s" % struct.pack("<HHH",len(data),repeat,offset)+data, wait=wait)
   1128 
   1129     def RFxmitLong(self, data, doencoding=True):

TypeError: can't concat str to bytes

sending command shoul be: d.RFxmit(b'\\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa')

Thanks for help

**Comment by andynoack** [comment]
Please try the rfcat_fix branch. Currently I do not have the rfcat environment configured, so this is just the fix you suggested. Can you confirm?

**Comment by BlessYou656** [comment]
Now its working thanks
