### ISSUE TITLE
Implement CRC plugin

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#86]
- New window
- Choose or define CRC polynomial
- Set CRC position (absolute or relative to the end)
- Choose range for input text (on basis of labels, or starting label + crc position)
- Return True/False

TODO:
- [ ] New category is named 'checksum'
  - [ ] CRC subcategory CRC type including CC1101 profile
  - [ ] Additional settings for CRC (textfields (hex): start value, final xor)
  - [ ] polynomial field should also be hex
  - [ ] enocean_hash subcategory with 4 bit, 8 bit enocean hash and crc8...radio button for autodetection (print rules for autodetection) and radio buttons to force one of the options
- [ ] New categories: hash, mac, error correcting codes, ...more?

**Comment by psa-jforestier** [comment]
Have a look at the CRC RevEng (http://reveng.sourceforge.net/) tool : a portable C program to compute CRC from an arbitrary input stream (can be an hex string on the command line) ; also have the hability to search for a CRC algorithm based on two or more input pattern (usefull to reverse engeneering an unknown protocol). Maybe it can be implemented as a Plugin in URH.

**Comment by andynoack** [comment]
Thank you for this advice! Indeed there is already an algorithm in the code that reverse engineers CRCs with the idea of Gregory Ewing (http://www.cosc.canterbury.ac.nz/greg.ewing/essays/CRC-Reverse-Engineering.html), but unfortunately I have not implemented a GUI (will probably be a plugin) for that yet. 

The problem with reverse engineering of CRCs is that it is very time consuming for larger polynomials which stands against the responsiveness of the GUI. This holds also for reveng. However, providing a plugin for CRC is an important point on our todo list :)
