### ISSUE TITLE
GPL-3.0 is a deprecated license

### ISSUE THREAD

**Issue by chenrui333** [jopohl/urh#871]
👋  it looks like the project is using an deprecated license, please consider using GPL-3.0-only or GPL-3.0-or-later. Thanks!

relates to Homebrew/homebrew-core#77331

**Comment by jopohl** [comment]
Can you be more specific? Just had a look at [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) and I see no differences to [our license](https://github.com/jopohl/urh/blob/master/LICENSE).

**Comment by SMillerDev** [comment]
It doesn't differ, this is specific to how Homebrew represents your license (which used a deprecated `SPDX` identifier), sorry for the noise

**Comment by jopohl** [comment]
No problem, closing this one.
