### ISSUE TITLE
Problem to activate RTL-SDR under Ubuntu 20.04

### ISSUE THREAD

**Issue by dwarning** [jopohl/urh#874]
##### Expected Behavior
Open the RTL-SDR USB Stick for Recording signals

##### Actual Behavior
If I activate the spectrum analyzer or the recorder I got:
RTLSDR-OPEN (#0): Error Code: -1 (-1)
RTLSDR: failed to start rx mode
BTW: same error if I not connect the stick into USB port.
All my other rtl-sdr tools are working: GQRX, Gnu Radio or rtl_433.
blacklist dvb_usb_rtl28xxu is there and rtl-sdr.rules is in /etc/udev/rules.d

##### Platform Specifications
 - OS: Ubuntu 20.04
 - URH version: 2.9.2
 - Python version: 3.8
 - Installed via Snap Store

**Comment by andynoack** [comment]
Have you tried starting as root?

**Comment by dwarning** [comment]
No sorry - I haven't. How can I do it?

 >urh works

 >sudo urh doesn't work - permission problems mkdir

I installed udev rules for this suite:

https://github.com/jopohl/urh/wiki/SDR-udev-rules

But no success so far.

Am 19.05.21 um 22:17 schrieb Prof. Dr. Andreas Noack:

**Comment by andynoack** [comment]
Be sure that you selected the native backend (not GR) in the device options. If there are permission problems you should run urh with sudo. Permission problems with sudo, but not without, sounds very strange.

**Comment by dwarning** [comment]
Yes - native backend is activated.

***@***.***:~$ urh

Qt: Session management error: Could not open network socket
[INFO::settings.py::get_receive_buffer_size] Allocate receive buffer 
with 262,144KB
[INFO::Device.py::start_rx_mode] RTLSDR: Starting RX Mode
[ERROR::Device.py::log_retcode] RTLSDR-OPEN (#0): Error Code: -1 (-1)
[INFO::Device.py::stop_rx_mode] RTLSDR: Stopping RX Mode: Dialog closed. 
Killing recording process.

***@***.***:~$ sudo urh
[sudo] Passwort für dietmar:
Testing for explicit PulseAudio choice...
Testing for ALSA permissions...
...use PulseAudio this time and ask next time.
mkdir: cannot create directory '/run/user/0': Permission denied
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path 
'/run/user/0/snap.urh', please create it with 0700 permissions.
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.


Am 19.05.21 um 23:08 schrieb Prof. Dr. Andreas Noack:

**Comment by andynoack** [comment]
Ok, maybe it's due to snap. Let's exclude that! Please try the git version or an installation with pip.

**Comment by dwarning** [comment]
OK, deinstalled the snap version and made the pip install.

But now:

***@***.***:~$ urh
Traceback (most recent call last):
   File "/usr/local/bin/urh", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.8/dist-packages/urh/main.py", line 84, 
in main
     import urh.cythonext.signal_functions
   File "src/urh/cythonext/signal_functions.pyx", line 1, in init 
urh.cythonext.signal_functions
ValueError: numpy.ndarray size changed, may indicate binary 
incompatibility. Expected 88 from C header, got 80 from PyObject

I have a fresh Ubuntu 20.04 with all the actual ingredients like numpy, 
cython etc.


Am 20.05.21 um 00:06 schrieb Prof. Dr. Andreas Noack:

**Comment by dwarning** [comment]
What a nightmare.

The problem was probably the numpy version 1.17 from the standard ubuntu 
distribution.

Found

pip3 install --upgrade numpy

to come to version 1.20.

Now URH runs and the dongle was found. Problem solved.

Thank you for your help.

Am 20.05.21 um 00:06 schrieb Prof. Dr. Andreas Noack:

**Comment by andynoack** [comment]
Sometimes it's the little things...Nice that it works now, closing here!
