### ISSUE TITLE
What is causing these dips in the demodulation interface?

### ISSUE THREAD

**Issue by karabijavad** [jopohl/urh#891]
##### Expected Behavior
No dips

##### Actual Behavior
Dips

##### Steps To Reproduce
Open demodulated tab. Sometimes there are dips

##### Screenshots
![Screenshot from 2021-07-15 13-44-19](https://user-images.githubusercontent.com/1298054/125840970-4069067b-6abf-4010-9311-1c731cf69d83.png)

##### Platform Specifications
 - OS: ubuntu 21
 - URH version: 2.9.1
 - Python version: 3.9
 - Installed via source

**Comment by andynoack** [comment]
These dips are usually caused by phase errors, in most cases due quality issues of the input signal.
