### ISSUE TITLE
Move bad signals to other group

### ISSUE THREAD

**Issue by hllhll** [jopohl/urh#900]
##### Is your feature request related to a problem?
This ticket It's basically some way to circumvent my issue in https://github.com/jopohl/urh/issues/899 please see there

##### Describe the solution you'd like
An alternative way to handle the data that is acceptable, is only using the data that was properly decoded. The only way that makes sense for me is that I'd use the synchronization and preamble as a "guide" of what are good messages and what aren't
I'd like to be able to move them to a separate group, or better yet, delete them.

I.E. If I'm capturing hundreds of bursts, I'd like to filter/move according to rather "preamble was not found" or was found

![image](https://user-images.githubusercontent.com/2906606/128244907-0591cf36-41ef-4d00-9a43-1548adea3298.png)

##### Additional context
https://github.com/jopohl/urh/issues/899

**Comment by andynoack** [comment]
You can already filter for the right preamble (everything else is temporarily not shown then), does that fix your problem?

**Comment by hllhll** [comment]
Whoo, Missed that! ^_^
