### ISSUE TITLE
I start URH from source code in rc.local on ubuntu18.

### ISSUE THREAD

**Issue by liuyg851119ase** [jopohl/urh#906]
##### Expected Behavior
I want to that URH start up from source code in rc.local on ubuntu18.04.

##### Actual Behavior
URH can't start up from source code in rc.local on ubuntu18.04

##### Screenshots
log:
Sep 19 11:07:13 x86-64 rc.local[1178]: qt.qpa.screen: QXcbConnection: Could not connect to display
Sep 19 11:07:13 x86-64 rc.local[1178]: Could not connect to any X display.
Sep 19 11:07:13 x86-64 systemd[1]: Stopping User Manager for UID 1000...
Sep 19 11:07:13 x86-64 systemd[1200]: Stopped target Default.
Sep 19 11:07:13 x86-64 systemd[1200]: Stopped target Basic System.
Sep 19 11:07:13 x86-64 systemd[1200]: Stopped target Timers.
Sep 19 11:07:13 x86-64 systemd[1200]: Stopped target Paths.
Sep 19 11:07:13 x86-64 systemd[1200]: Stopped Pending report trigger for Ubuntu Report.
Sep 19 11:07:13 x86-64 systemd[1200]: Stopped target Sockets.
Sep 19 11:07:13 x86-64 systemd[1200]: Closed REST API socket for snapd user session agent.
Sep 19 11:07:13 x86-64 systemd[1200]: Closed GnuPG cryptographic agent and passphrase cache.
Sep 19 11:07:13 x86-64 systemd[1200]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Sep 19 11:07:13 x86-64 systemd[1200]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Sep 19 11:07:13 x86-64 systemd[1200]: Closed D-Bus User Message Bus Socket.
Sep 19 11:07:13 x86-64 systemd[1200]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Sep 19 11:07:13 x86-64 systemd[1200]: Closed GnuPG network certificate management daemon.
Sep 19 11:07:13 x86-64 systemd[1200]: Reached target Shutdown.
Sep 19 11:07:13 x86-64 systemd[1200]: Starting Exit the Session...
Sep 19 11:07:13 x86-64 systemd[1200]: Received SIGRTMIN+24 from PID 1333 (kill).
Sep 19 11:07:13 x86-64 systemd[1]: Stopped User Manager for UID 1000.
Sep 19 11:07:13 x86-64 systemd[1]: Removed slice User Slice of vecentek.

It seem to be Qt lib issue.
##### Platform Specifications
ubuntu18.04

I am looking forward to getting some help.

   Tks!
BR

**Comment by andynoack** [comment]
I am sorry, this is a usage error. Please use the latest distributions (18.04 is pretty old) and read a tutorial on how to start graphical programs from shell scripts.
