### ISSUE TITLE
Signal list not scrollable

### ISSUE THREAD

**Issue by Apokalypser** [jopohl/urh#972]
##### Expected Behavior
I have six signals opened, but can only see four and a half. Scrolling down enables me to see the other signals.

##### Actual Behavior
I have i.e. six signals opened, but can only see four and a half. Scrolling down the list to see the rest of the signals is not possible.

##### Steps To Reproduce
Open six signals
Try to scroll down

##### Screenshots
<img width="3346" alt="Bildschirmfoto 2022-03-24 um 15 31 28" src="https://user-images.githubusercontent.com/2430749/159939239-df7719ff-76f0-4858-b36d-d935541ee5b1.png">

##### Platform Specifications
 - OS: macOS 12.1
 - URH version: 2.9.3
 - Python version: 2.7.18
 - Installed via download of dmg

**Comment by andynoack** [comment]
I cannot reproduce this behaviour (just tested with linux). Have you tried a clean reinstallation?

**Comment by Apokalypser** [comment]
Yes, just downloaded 2.9.3. Maybe it's a macOS-only bug?

**Comment by andynoack** [comment]
Would you try the git version?

**Comment by Apokalypser** [comment]
I tried the git version. It supports darkmode now, but the signal list still is not scrollable.

**Comment by andynoack** [comment]
That seems to be a macOS bug. Can anyone with a MAC confirm that?

**Comment by Apokalypser** [comment]
I can confirm that. After connecting a USB mouse a scrollbar is displayed which enables scrolling. Scrolling on the plain GUI is still not possible. Activating the scrollbar is also possible by setting "Always show scrollbars" in macOS.
