### ISSUE TITLE
Starting urh.exe throws an exception

### ISSUE THREAD

**Issue by DoganM95** [jopohl/urh#976]
##### Expected Behavior
Should start normally

##### Actual Behavior
Starting urh.exe throws an exception

##### Steps To Reproduce
1. Install URH
2. double click urh.exe in install folder

##### Screenshots
![image](https://user-images.githubusercontent.com/38842553/165150036-5d506445-f333-42c3-b42d-fc61b34dc658.png)

##### Platform Specifications
 - OS: Windows 10
 - URH version: 2.9.3
 - Python version: 3.10.3
 - Installed via GitHub Release (x64 exe)

**Comment by andynoack** [comment]
Can someone confirm? I cannot reproduce this error.

**Comment by DoganM95** [comment]
Just fixed this by deleting the `.../Appdata/Roaming/urh` folder.
Seems like my config was messed up or something, just in case anyone runs into this in the future.
